In [1]:
import json 
from pathlib import Path
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
from metrics import (
    mean_average_precision_score,
    F1_score_from_sim,
    IoU_from_sim,
    IoU_q
)

%load_ext autoreload
%autoreload 2

In [2]:
output_folder = Path("/media/eceo_scratch_haas001/results/CLIP4Clip/test/")
gt_json = Path("../zero_shot/CLIP4Clip/dataset/test/ground_truth.json")
with open(gt_json, "r") as f:
    gt_queries_videos = json.load(f)
queries = gt_queries_videos.keys()
sim_matrix_df = pd.read_csv(output_folder / "similarity_matrix.csv").set_index("video_id")
sim_matrix_df

,An animal engaged in any activity other than foraging.,An animal that is neither a red deer nor a roe deer.,An animal running.,An animal bathing.,A roe deer grazing.,An animal browsing.,An adult roe deer sniffing.,A juvenile red deer scratching its body.,A chamois trotting.,An adult male roe deer jumping.,...,An animal running while reacting to a camera.,An animal looking at a camera.,An animal reacting to a camera and then foraging.,"An animal foraging, then reacting to a camera, and then returning to foraging.",An animal reacting to a camera and then running away.,"An animal foraging, then reacting to a camera, and then running away.",An animal reacting to a camera in rainy or overcast weather.,An animal reacting to a camera in clear or sunny weather.,A single adult red deer foraging only.,An empty video.
video_id,,,,,,,,,,,,,,,,,,,,,
S1_C1_E100_V0251,22.025024,23.058090,23.182589,19.843180,22.673430,20.422297,22.582565,21.165018,23.312788,22.198380,...,22.866163,19.838554,25.505990,26.224625,23.038357,25.728630,26.414658,23.696938,25.384617,24.381996
S1_C1_E103_V0253,25.327059,25.812813,24.681633,19.453003,25.737038,23.393959,24.397135,24.020302,22.956180,24.664598,...,26.388105,23.744965,28.624557,28.623095,27.176434,29.404380,24.152350,21.749860,26.057178,22.562260
S1_C1_E103_V0254,27.366703,27.258469,25.552150,20.729197,27.250528,24.342224,26.422905,26.267862,25.795517,25.703081,...,26.886086,24.648014,29.865953,29.831013,27.782090,30.702028,24.998377,22.821041,27.432146,20.780462
S1_C1_E103_V0255,26.163033,26.442957,24.768353,20.247803,26.607132,24.112444,25.912556,25.335983,24.365292,25.056978,...,26.395887,24.453623,29.000748,28.851583,27.379921,29.891031,24.234856,21.930916,26.565964,21.234852
S1_C1_E103_V0256,25.339710,25.402850,24.501010,19.609590,25.393260,23.367579,24.657450,23.956980,22.942724,24.738043,...,26.289034,23.753078,28.601917,28.534672,27.102724,29.495611,23.785587,21.538057,25.635607,22.011032
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
S3_C5_F719_V0154,25.470102,26.937819,24.194810,21.579111,28.781870,24.375721,28.479935,26.792372,23.607350,25.945854,...,26.644240,25.773058,29.412035,28.974236,27.417547,29.341835,26.338520,24.864092,27.032345,21.845661
S3_C5_F719_V0155,25.468456,26.781973,24.589520,21.392715,28.630522,24.555481,28.577590,26.747175,24.265448,26.501148,...,26.879490,25.703505,29.425930,28.922356,27.489489,29.292034,25.960180,24.640420,26.998362,22.137127
S3_C5_F719_V0156,25.220602,26.415209,24.586687,21.490332,28.541178,24.518880,28.391330,26.153364,24.014305,26.312240,...,26.471355,25.480057,29.034618,28.603899,27.085728,28.868706,25.779320,24.389738,26.638830,22.406485
S3_C5_F719_V0157,25.363928,26.813630,24.850560,21.559890,29.216734,24.574697,28.832127,27.000480,24.617440,26.814371,...,26.488993,25.562754,28.809917,28.326956,27.075481,28.655120,25.963446,24.694120,27.144850,22.325779
S3_C5_F719_V0158,25.219425,26.646194,24.804580,21.163290,28.830614,24.467130,28.469425,26.598206,24.146585,26.676447,...,26.483356,25.442204,28.774422,28.309800,27.109093,28.746054,25.642725,24.346710,26.996723,22.565237

# mAP

In [3]:
mAP, APs = mean_average_precision_score(gt_queries_videos, sim_matrix_df)
print(f"mAP queries: {mAP: .3f}")
sorted(APs.items(), key=lambda x:x[1], reverse=True)

mAP queries:  0.089

[('An animal being vigilant while the weather is rainy or overcast.',
  0.5815419249864335),
 ('An animal engaged in any activity other than foraging.',
  0.5642802407400905),
 ('Rainy weather.', 0.3875653699117429),
 ('A single adult red deer foraging only.', 0.38682948634615816),
 ('An adult red deer standing with its head up while participating in courtship.',
  0.3103757372141977),
 ('An adult red deer vocalizing while participating in courtship.',
  0.2996077322123413),
 ('An animal participating in courtship.', 0.2582176148545082),
 ('A video of three or more red deer.', 0.24425774164699032),
 ('A red deer foraging in sunny weather.', 0.22771518176472808),
 ('A red deer foraging in rainy weather.', 0.22329565563352702),
 ('A juvenile red deer playing.', 0.222275641025641),
 ('An adult male red deer being vigilant after vocalizing.',
  0.21775261485911168),
 ('Two or more animals reacting to a camera.', 0.2),
 ('A video of two or more animals.', 0.19350317278504692),
 ('An animal reacting to a camera in rainy or overcast weather.',
  0.1931497529583654),
 ('A video of two or more juvenile red deer.', 0.18541065460083958),
 ('An animal being vigilant while the weather is clear or sunny.',
  0.18502254186645545),
 ('An adult male red deer running while participating in courtship.',
  0.1817299802554201),
 ('An animal running.', 0.18039263834686678),
 ('An adult female red deer running while participating in courtship.',
  0.17665515960697786),
 ('A video of an animal drinking.', 0.16645808997096104),
 ('A juvenile red deer scratching its body.', 0.16640092630901612),
 ('An adult female red deer foraging and a juvenile red deer foraging.',
  0.16250097058403898),
 ('A juvenile red deer doing at least one different action than an adult female red deer.',
  0.15445917585192664),
 ('An adult red deer reacting to a camera.', 0.14152208747081899),
 ('An adult male red deer rubbing its antlers on the ground.',
  0.13497797666068437),
 ('An animal reacting to a camera.', 0.12594892849001416),
 ('An animal reacting to a camera and then running away.',
  0.12401015896114136),
 ('An adult male red deer pawing the ground while wallowing.',
  0.11614865356017316),
 ('An animal looking at a camera.', 0.11100774124092902),
 ('An adult male red deer reacting to a camera.', 0.10854162016410722),
 ('A video of two red deer.', 0.10746290796035891),
 ('An adult male red deer pawing the ground and rubbing its antlers on the ground while wallowing.',
  0.10366722064163039),
 ('A video of one adult male and one adult female red deer running while participating in courtship.',
  0.09851745576279292),
 ('An animal bathing.', 0.09133095768263315),
 ('A video of two adult female red deer walking while foraging.',
  0.0910174027058813),
 ('An animal running while foraging.', 0.08323317291004542),
 ('An animal reacting to a camera in clear or sunny weather.',
  0.07920433262635529),
 ('Two or more red deer foraging, with at least one also being vigilant at some point.',
  0.07911023669439939),
 ('An animal bathing while grooming.', 0.0779739386262111),
 ('A roe deer foraging in rainy weather.', 0.07045647558386411),
 ('A juvenile deer in clear or sunny weather.', 0.06937189572044561),
 ('A video of two or more red deer escaping.', 0.06864901669455632),
 ('An animal running while reacting to a camera.', 0.06797544799286394),
 ('An animal reacting to a camera and then foraging.', 0.06399406370194846),
 ('An adult female red deer reacting to a camera.', 0.060547616242499804),
 ('A juvenile red deer doing the exact same activities as an adult female red deer.',
  0.054374249464521816),
 ('A juvenile red deer doing the exact same actions as an adult female red deer.',
  0.047896787779288616),
 ('An empty video.', 0.04645758336891037),
 ('An animal foraging, then reacting to a camera, and then running away.',
  0.04038849166235594),
 ('An animal foraging, then reacting to a camera, and then returning to foraging.',
  0.03840991886005279),
 ('An animal browsing.', 0.03674166265278797),
 ('An animal resting.', 0.03323696068306941),
 ('An adult male red deer urinating while wallowing.', 0.03216675244467319),
 ('A roe deer trotting while foraging.', 0.02958847041817942),
 ('A roe deer foraging in sunny weather.', 0.029032556254075997),
 ('A video of three or more red deer reacting to a camera.',
  0.02857142857142857),
 ('A video of an animal lying down while resting.', 0.02691581978655818),
 ('An adult male red deer bathing while wallowing.', 0.025),
 ('A juvenile red deer walking while being vigilant.', 0.02452249005453312),
 ('A wolf foraging.', 0.022108843537414963),
 ('An adult red deer lying down while participating in courtship.',
  0.021739130434782608),
 ('An animal that is neither a red deer nor a roe deer.',
  0.016071190727221588),
 ('A marten.', 0.015572436245252307),
 ('A juvenile deer in rainy weather.', 0.014265536570085374),
 ('A fox foraging.', 0.013405054644808744),
 ('A video of an individual sniffing while reacting to a camera.',
  0.01277652745394681),
 ('A red deer vocalizing in rainy weather.', 0.012199411641702974),
 ('A red deer participating in courtship in rainy weather.',
  0.01193745775557923),
 ('A roe deer grazing.', 0.010967190938063162),
 ('A juvenile deer reacting to a camera.', 0.01023679263568466),
 ('A chamois.', 0.009055292033518474),
 ('An adult roe deer sniffing.', 0.00869388030528004),
 ('A hare.', 0.007992467038567874),
 ('A red deer resting in clear weather.', 0.007653193103365083),
 ('A video of two or more wolves.', 0.007633587786259542),
 ('A hare foraging.', 0.006914677396108014),
 ('A red deer resting in rainy weather.', 0.006435044137176783),
 ('A red deer browsing.', 0.00641025641025641),
 ('An adult red deer browsing.', 0.005952380952380952),
 ('A mountain hare being vigilant.', 0.005257634761466323),
 ('A wolf chasing prey.', 0.004832750603633584),
 ('An animal escaping from another animal of the same species that is chasing it.',
  0.004415344200704475),
 ('A chamois being vigilant.', 0.0036772050744181403),
 ('A video showing individuals from at least two different species.',
  0.003494281842715565),
 ('A video of one adult male and one adult female roe deer running while participating in courtship.',
  0.0034477366093427666),
 ('A wolf chasing prey in overcast or rainy weather.', 0.0030734222155077992),
 ('An adult female roe deer running while participating in courtship.',
  0.002967072493639514),
 ('An adult male roe deer running while participating in courtship.',
  0.0029076923584775106),
 ('A roe deer participating in courtship in clear weather.',
  0.002771810397051264),
 ('A chamois trotting.', 0.002730146896399381),
 ('A juvenile red deer nursing.', 0.0026737013450609704),
 ('A wolf chasing prey in clear or sunny weather.', 0.0025981514737136923),
 ('An animal stretching its body.', 0.002489124619070882),
 ('An animal escaping from another animal of a different species that is chasing it.',
  0.0024098545936664566),
 ('An adult female red deer nursing.', 0.002381421626593089),
 ('A juvenile red deer suckling.', 0.002331002331002331),
 ('An adult male roe deer jumping.', 0.002219199739601497),
 ('A mountain hare grazing.', 0.0015698587127158557),
 ('An adult roe deer reacting to a camera.', 0.0013869625520110957)]

# mIoU and F1-score (require threshold)

Find the optimal threshold per query on train set

In [6]:
gt_json_train = Path("../zero_shot/CLIP4Clip/dataset/train/ground_truth.json")
output_folder_train = Path("/media/eceo_scratch_haas001/results/CLIP4Clip/train")
with open(gt_json_train, "r") as f:
    gt_queries_videos_train = json.load(f)
queries = gt_queries_videos_train.keys()
sim_matrix_train_df = pd.read_csv(output_folder_train / "similarity_matrix.csv").set_index("video_id")
sim_matrix_train_df

,An animal engaged in any activity other than foraging.,An animal that is neither a red deer nor a roe deer.,An animal running.,An animal bathing.,A roe deer grazing.,An animal browsing.,An adult roe deer sniffing.,A juvenile red deer scratching its body.,A chamois trotting.,An adult male roe deer jumping.,...,An animal looking at a camera.,A wolf reacting to a camera.,An animal reacting to a camera and then foraging.,"An animal foraging, then reacting to a camera, and then returning to foraging.",An animal reacting to a camera and then running away.,"An animal foraging, then reacting to a camera, and then running away.",An animal reacting to a camera in rainy or overcast weather.,An animal reacting to a camera in clear or sunny weather.,A single adult red deer foraging only.,An empty video.
video_id,,,,,,,,,,,,,,,,,,,,,
S1_C1_E104_V0262,25.047344,25.285330,24.552656,19.309107,25.557714,23.111443,24.132568,23.560472,23.293472,24.497710,...,23.193817,26.580597,28.561604,28.724882,26.789042,29.312930,24.176136,21.585636,25.889946,22.138681
S1_C1_E104_V0263,25.129768,25.339550,24.524174,19.191492,25.660034,23.132143,24.256533,23.835802,23.466125,24.599577,...,23.208872,26.523512,28.671432,28.804660,26.872340,29.384876,23.854362,21.573840,26.074451,22.180128
S1_C1_E104_V0264,25.215635,25.479912,24.454012,19.105349,25.930750,23.100508,24.516160,24.137667,23.504972,24.822218,...,23.219446,26.515522,28.687931,28.771246,26.810583,29.366306,23.872883,21.607199,26.286346,22.095740
S1_C1_E104_V0265,24.801502,25.055367,24.013224,19.131226,25.326508,22.826614,23.900690,23.351688,22.770237,24.287825,...,22.743216,26.349660,28.538345,28.910583,26.625925,29.485788,23.873444,21.284311,25.750320,22.330738
S1_C1_E104_V0266,24.824814,25.172010,24.430773,19.113312,25.508318,22.973051,23.982685,23.508600,22.924400,24.311130,...,22.993132,26.311255,28.442360,28.654593,26.644493,29.164284,23.868908,21.408472,25.840040,22.268000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
S3_C5_F930_V0504,25.411633,23.717402,26.792934,21.728666,25.432741,23.784174,24.181986,24.825504,26.065847,24.998274,...,23.933980,26.835802,27.266258,27.431879,26.529785,27.983269,21.944809,26.905596,27.454037,26.286762
S3_C5_F934_V0508,25.585928,23.728724,25.865635,20.917130,23.433332,23.601980,23.073425,24.126307,28.579414,23.537483,...,24.173534,24.899780,26.104073,25.758759,24.384851,25.410519,21.625284,25.993470,25.416970,22.962930
S3_C5_F953_V0782,25.353405,23.930891,26.264364,20.716549,24.314304,23.411760,23.492044,24.640018,28.975788,23.809994,...,23.889204,24.640005,25.862047,25.570848,23.809603,24.957440,21.234713,25.961480,26.143545,23.008465
S3_C6_F633_V0019,27.452475,29.264227,26.529694,20.685925,29.833427,24.524666,28.994730,28.145908,26.532217,27.935717,...,25.342093,26.247993,30.139784,30.228678,27.943054,30.876550,26.211267,23.510029,29.400253,21.116350
S3_C6_F633_V0020,26.101967,27.802185,25.927258,20.834790,28.011778,23.819756,26.819408,26.436508,24.840467,25.621960,...,24.664375,25.751066,29.549105,29.655827,27.700523,30.218197,25.888607,22.756182,27.697826,22.124990

In [7]:
thrs = np.arange(sim_matrix_train_df.values.min(), sim_matrix_train_df.values.max(), step=0.5)
best_t = dict.fromkeys(gt_queries_videos_train.keys())
for q in gt_queries_videos_train.keys():
    best_IoU = 0
    if q not in sim_matrix_train_df.columns:
        print(f"Query {q} has not been processed")
        continue
    gt_videos_q = list(gt_queries_videos_train[q]["videos"])
    for t in thrs:
        ass_videos_q = list(sim_matrix_train_df.index[sim_matrix_train_df[q] > t])
        iou = IoU_q(gt_videos_q, ass_videos_q)
        if not np.isnan(iou) and iou > best_IoU:
            best_IoU = iou
            best_t[q] = t
    
    if best_t[q] is None:
        print(f"No best threshold found for {q}, using median similarity score as threshold")
        best_t[q] = np.median(sim_matrix_train_df.values)

In [ ]:
mF1, F1_queries = F1_score_from_sim(gt_queries_videos=gt_queries_videos, sim_matrix_df=sim_matrix_df, best_thresholds=best_t)
mIoU, IoU_queries = IoU_from_sim(gt_queries_videos=gt_queries_videos, sim_matrix_df=sim_matrix_df, best_thresholds=best_t)

In [19]:
print(f"F1-score (macro-avg.): {mF1:.2f}")
print(f"mean IoU: {mIoU:.2f}")

F1-score (macro-avg.): 0.09
mean IoU: 0.05

In [33]:
results_df = pd.concat([
    pd.DataFrame.from_dict(IoU_queries, orient="index", columns=["mIoU"]),
    pd.DataFrame.from_dict(F1_queries, orient="index", columns=["F1-score"])
], axis=1)

pd.set_option('display.max_rows', 100)
pd.set_option('display.max_colwidth', 90)
results_df.sort_values("mIoU", ascending=False)

,mIoU,F1-score
A single adult red deer foraging only.,0.476129,0.645105
An animal being vigilant while the weather is rainy or overcast.,0.406250,0.577778
An animal engaged in any activity other than foraging.,0.404092,0.575592
An adult red deer standing with its head up while participating in courtship.,0.250000,0.400000
An animal participating in courtship.,0.228070,0.371429
An adult red deer vocalizing while participating in courtship.,0.225564,0.368098
A video of an animal drinking.,0.187500,0.315789
An adult male red deer being vigilant after vocalizing.,0.171875,0.293333
An animal being vigilant while the weather is clear or sunny.,0.150968,0.262332
Rainy weather.,0.139355,0.244621
An adult male red deer pawing the ground while wallowing.,0.129032,0.228571
A video of two or more animals.,0.125485,0.222989
A video of three or more red deer.,0.125000,0.222222
An adult male red deer rubbing its antlers on the ground.,0.118812,0.212389
An animal running.,0.116766,0.209115
A video of two or more juvenile red deer.,0.114286,0.205128
A red deer foraging in sunny weather.,0.112676,0.202532
A red deer foraging in rainy weather.,0.102094,0.185273
A juvenile red deer scratching its body.,0.100000,0.181818
A video of two red deer.,0.095064,0.173623
A video of two adult female red deer walking while foraging.,0.083333,0.153846
An adult male red deer pawing the ground and rubbing its antlers on the ground while wallowing.,0.080000,0.148148
An animal reacting to a camera.,0.071429,0.133333
A juvenile red deer playing.,0.067797,0.126984
An animal looking at a camera.,0.066667,0.125000
A juvenile red deer doing at least one different action than an adult female red deer.,0.066667,0.125000
An adult female red deer foraging and a juvenile red deer foraging.,0.064706,0.121547
A juvenile deer in clear or sunny weather.,0.063652,0.119685
An animal running while foraging.,0.062500,0.117647
An animal reacting to a camera and then foraging.,0.062500,0.117647
An adult red deer reacting to a camera.,0.057971,0.109589
"An animal foraging, then reacting to a camera, and then returning to foraging.",0.050000,0.095238
An animal reacting to a camera in rainy or overcast weather.,0.050000,0.095238
An adult female red deer running while participating in courtship.,0.048387,0.092308
An animal reacting to a camera in clear or sunny weather.,0.047619,0.090909
An animal browsing.,0.043478,0.083333
"Two or more red deer foraging, with at least one also being vigilant at some point.",0.042821,0.082126
An adult male red deer running while participating in courtship.,0.039683,0.076336
An adult male red deer reacting to a camera.,0.038168,0.073529
An empty video.,0.037594,0.072464
Two or more animals reacting to a camera.,0.034483,0.066667
A roe deer foraging in sunny weather.,0.033333,0.064516
A roe deer trotting while foraging.,0.032258,0.062500
An animal bathing while grooming.,0.028571,0.055556
A juvenile red deer doing the exact same actions as an adult female red deer.,0.027778,0.054054
An animal that is neither a red deer nor a roe deer.,0.025873,0.050441
An animal reacting to a camera and then running away.,0.022727,0.044444
An adult male red deer bathing while wallowing.,0.022222,0.043478
An animal running while reacting to a camera.,0.022099,0.043243
An adult red deer lying down while participating in courtship.,0.021739,0.042553
A juvenile red deer walking while being vigilant.,0.021739,0.042553
An adult female red deer reacting to a camera.,0.020761,0.040678
An animal resting.,0.018692,0.036697
A roe deer grazing.,0.013175,0.026008
"An animal foraging, then reacting to a camera, and then running away.",0.012987,0.025641
An adult roe deer sniffing.,0.012048,0.023810
A fox foraging.,0.011765,0.023256
A roe deer foraging in rainy weather.,0.011494,0.022727
A red deer vocalizing in rainy weather.,0.009901,0.019608
A red deer participating in courtship in rainy weather.,0.007937,0.015748
A juvenile red deer doing the exact same activities as an adult female red deer.,0.007874,0.015625
A wolf foraging.,0.007273,0.014440
A hare.,0.006667,0.013245
A video of one adult male and one adult female red deer running while participating in courtship.,0.006612,0.013136
A red deer browsing.,0.005988,0.011905
A chamois.,0.005618,0.011173
A hare foraging.,0.005413,0.010767
A video showing individuals from at least two different species.,0.004000,0.007968
A roe deer participating in courtship in clear weather.,0.003876,0.007722
A red deer resting in clear weather.,0.003546,0.007067
A mountain hare being vigilant.,0.003396,0.006768
A red deer resting in rainy weather.,0.003221,0.006421
An animal escaping from another animal of a different species that is chasing it.,0.002882,0.005747
An adult female red deer nursing.,0.002706,0.005398
A wolf chasing prey in clear or sunny weather.,0.002053,0.004098
An animal stretching its body.,0.001667,0.003328
A juvenile red deer nursing.,0.001508,0.003012
A video of two or more wolves.,0.001441,0.002878
A juvenile red deer suckling.,0.001420,0.002837
A video of three or more red deer reacting to a camera.,0.001337,0.002670
A chamois trotting.,0.000000,0.000000
An animal bathing.,0.000000,0.000000
An adult red deer browsing.,0.000000,0.000000
A chamois being vigilant.,0.000000,0.000000
A juvenile deer in rainy weather.,0.000000,0.000000
A video of an animal lying down while resting.,0.000000,0.000000
A mountain hare grazing.,0.000000,0.000000
An adult male roe deer jumping.,0.000000,0.000000
A wolf chasing prey.,0.000000,0.000000
A marten.,0.000000,0.000000
An adult male roe deer running while participating in courtship.,0.000000,0.000000
A video of one adult male and one adult female roe deer running while participating in courtship.,0.000000,0.000000
An animal escaping from another animal of the same species that is chasing it.,0.000000,0.000000
A video of two or more red deer escaping.,0.000000,0.000000
An adult female roe deer running while participating in courtship.,0.000000,0.000000
An adult male red deer urinating while wallowing.,0.000000,0.000000
An adult roe deer reacting to a camera.,0.000000,0.000000
A wolf chasing prey in overcast or rainy weather.,0.000000,0.000000
A video of an individual sniffing while reacting to a camera.,0.000000,0.000000
A juvenile deer reacting to a camera.,0.000000,0.000000