In [2]:
import json 
from pathlib import Path
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
from metrics import (
    mean_average_precision_score,
    F1_score_from_sim,
    IoU_from_sim,
    IoU_q
)

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [3]:
output_folder = Path("/media/eceo_scratch_haas001/results/GRAM/test/")
gt_json = Path("../zero_shot/GRAM/dataset/test/ground_truth.json")
with open(gt_json, "r") as f:
    gt_queries_videos = json.load(f)
queries = gt_queries_videos.keys()
sim_matrix_df = pd.read_csv(output_folder / "similarity_matrix.csv").set_index("video_id")
sim_matrix_df

,An animal engaged in any activity other than foraging.,An animal that is neither a red deer nor a roe deer.,An animal running.,An animal bathing.,A roe deer grazing.,An animal browsing.,An adult roe deer sniffing.,A juvenile red deer scratching its body.,A chamois trotting.,An adult male roe deer jumping.,...,An animal running while reacting to a camera.,An animal looking at a camera.,An animal reacting to a camera and then foraging.,"An animal foraging, then reacting to a camera, and then returning to foraging.",An animal reacting to a camera and then running away.,"An animal foraging, then reacting to a camera, and then running away.",An animal reacting to a camera in rainy or overcast weather.,An animal reacting to a camera in clear or sunny weather.,A single adult red deer foraging only.,An empty video.
video_id,,,,,,,,,,,,,,,,,,,,,
S1_C1_E100_V0251,-0.964568,-0.961597,-0.952266,-0.980965,-0.923261,-0.955397,-0.917335,-0.938462,-0.982236,-0.922038,...,-0.928584,-0.961291,-0.941749,-0.938528,-0.932865,-0.919049,-0.937883,-0.950716,-0.925142,-0.971212
S1_C1_E103_V0253,-0.951148,-0.941746,-0.945132,-0.981318,-0.907478,-0.939549,-0.882842,-0.894601,-0.978788,-0.903049,...,-0.906029,-0.940912,-0.903619,-0.899757,-0.903650,-0.878225,-0.936607,-0.945256,-0.903484,-0.978220
S1_C1_E103_V0254,-0.952355,-0.932866,-0.952997,-0.981669,-0.873903,-0.945276,-0.852483,-0.866660,-0.977661,-0.884220,...,-0.923407,-0.951035,-0.911055,-0.904689,-0.920603,-0.888999,-0.943775,-0.953489,-0.867109,-0.977110
S1_C1_E103_V0255,-0.948939,-0.932381,-0.952913,-0.977354,-0.866531,-0.943453,-0.849721,-0.866036,-0.979003,-0.884299,...,-0.922723,-0.948307,-0.907669,-0.900658,-0.919186,-0.886198,-0.941576,-0.950323,-0.864508,-0.968629
S1_C1_E103_V0256,-0.948559,-0.932052,-0.952589,-0.976928,-0.864149,-0.944096,-0.851098,-0.866564,-0.978467,-0.884846,...,-0.922127,-0.948372,-0.907211,-0.899488,-0.919087,-0.885128,-0.941727,-0.949407,-0.862256,-0.972184
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
S3_C5_F719_V0158,-0.960674,-0.960770,-0.944474,-0.984108,-0.939287,-0.952636,-0.922327,-0.926022,-0.981058,-0.916575,...,-0.902114,-0.955633,-0.915680,-0.913919,-0.901925,-0.884471,-0.943960,-0.950835,-0.935103,-0.973035
S3_C5_F863_V0178,-0.957484,-0.956498,-0.952128,-0.983740,-0.926997,-0.955516,-0.908466,-0.916218,-0.980849,-0.921869,...,-0.900207,-0.953532,-0.910122,-0.906496,-0.903225,-0.881934,-0.938329,-0.941996,-0.925886,-0.975967
S3_C5_F863_V0179,-0.956349,-0.934005,-0.949077,-0.983671,-0.895845,-0.945407,-0.864377,-0.875700,-0.976425,-0.890753,...,-0.907169,-0.941338,-0.904968,-0.905062,-0.906887,-0.884456,-0.937118,-0.945468,-0.886179,-0.978204
S3_C5_F863_V0180,-0.962046,-0.968357,-0.957902,-0.982756,-0.948993,-0.966080,-0.941040,-0.942179,-0.975763,-0.947468,...,-0.907805,-0.957633,-0.920198,-0.916156,-0.912299,-0.897912,-0.937977,-0.940927,-0.946556,-0.972780
S3_C5_F884_V0195,-0.980928,-0.985765,-0.973659,-0.996010,-0.954617,-0.985664,-0.962934,-0.967203,-0.992551,-0.950965,...,-0.967197,-0.984196,-0.979626,-0.971612,-0.978240,-0.966502,-0.989692,-0.979324,-0.960962,-0.973184

# mAP

In [7]:
mAP, APs = mean_average_precision_score(gt_queries_videos, sim_matrix_df)
print(f"mAP queries: {mAP: .3f}")
sorted(APs.items(), key=lambda x:x[1], reverse=True)

mAP queries:  0.060

[('An animal engaged in any activity other than foraging.',
  0.20964543768445545),
 ('A juvenile red deer playing.', nan),
 ('An animal resting.', 0.3054147628219026),
 ('A red deer resting in rainy weather.', nan),
 ('Rainy weather.', 0.4896618124157301),
 ('A video of an animal lying down while resting.', 0.2666698194962562),
 ('An adult male red deer rubbing its antlers on the ground.',
  0.09674954726244209),
 ('An animal running.', 0.06544179132506622),
 ('An animal participating in courtship.', 0.06149107125491292),
 ('An adult red deer standing with its head up while participating in courtship.',
  0.05797362126761152),
 ('An adult red deer vocalizing while participating in courtship.',
  0.056734550693912075),
 ('A juvenile deer in clear or sunny weather.', 0.056105122721568895),
 ('An animal bathing.', 0.038990122774568904),
 ('A wolf foraging.', 0.029392712550607287),
 ('An animal running while foraging.', 0.025101463339484018),
 ('An adult red deer browsing.', 0.025),
 ('A red deer browsing.', 0.01694915254237288),
 ('An animal that is neither a red deer nor a roe deer.',
  0.015227968606784686),
 ('A wolf chasing prey.', 0.013760292838283427),
 ('An animal bathing while grooming.', 0.012630849563925569),
 ('A video of an animal drinking.', 0.010505348258629577),
 ('A roe deer trotting while foraging.', 0.010121962756210452),
 ('A roe deer grazing.', 0.009023766313703208),
 ('An animal browsing.', 0.008392240261987233),
 ('A juvenile red deer scratching its body.', 0.007971204461127231),
 ('A chamois.', 0.005425624433599101),
 ('A red deer resting in clear weather.', 0.0051437458626211845),
 ('An adult roe deer sniffing.', 0.004552304416515524),
 ('A hare.', 0.004293164973259857),
 ('A hare foraging.', 0.0035882693874690528),
 ('A mountain hare being vigilant.', 0.0029049163447412937),
 ('An adult male roe deer jumping.', 0.0028930975375224717),
 ('An animal stretching its body.', 0.0027577829085366776),
 ('A fox foraging.', 0.002512409316533028),
 ('A juvenile deer in rainy weather.', 0.0023570491047722104),
 ('A chamois trotting.', 0.0023489733750049454),
 ('A marten.', 0.0021755188913950285),
 ('A chamois being vigilant.', 0.002148164511620321),
 ('A mountain hare grazing.', 0.0013717421124828531),
 ('An adult red deer lying down while participating in courtship.', nan),
 ('An adult male red deer running while participating in courtship.', nan),
 ('An adult female red deer running while participating in courtship.',
  0.001597444089456869),
 ('A video of one adult male and one adult female red deer running while participating in courtship.',
  nan),
 ('An adult male roe deer running while participating in courtship.', nan),
 ('An adult female roe deer running while participating in courtship.', nan),
 ('A video of one adult male and one adult female roe deer running while participating in courtship.',
  nan),
 ('An adult male red deer pawing the ground and rubbing its antlers on the ground while wallowing.',
  0.024460865902269882),
 ('An adult male red deer pawing the ground while wallowing.',
  0.021475993103309027),
 ('An adult male red deer bathing while wallowing.', nan),
 ('An adult male red deer urinating while wallowing.', nan),
 ('A red deer vocalizing in rainy weather.', nan),
 ('A roe deer participating in courtship in clear weather.', nan),
 ('A red deer participating in courtship in rainy weather.', nan),
 ('An adult female red deer foraging and a juvenile red deer foraging.',
  0.33829276664152363),
 ('A video of two red deer.', 0.3295842867110144),
 ('Two or more animals reacting to a camera.', nan),
 ('A video of three or more red deer reacting to a camera.', nan),
 ('A single adult red deer foraging only.', 0.45043775229543137),
 ('A juvenile red deer doing the exact same actions as an adult female red deer.',
  0.24400887894030565),
 ('A juvenile red deer doing the exact same activities as an adult female red deer.',
  0.2208470462438406),
 ('An animal reacting to a camera and then running away.',
  0.20397203834995356),
 ('A video of two or more animals.', 0.18499277890107843),
 ('A juvenile red deer doing at least one different action than an adult female red deer.',
  0.13658462000951052),
 ('A video of an individual sniffing while reacting to a camera.',
  0.10569698442085372),
 ('An animal running while reacting to a camera.', 0.10404387556943005),
 ('A red deer foraging in rainy weather.', 0.10393496208941506),
 ('An animal being vigilant while the weather is clear or sunny.',
  0.1033050126772149),
 ('An adult female red deer reacting to a camera.', 0.0978241650440473),
 ('An adult red deer reacting to a camera.', 0.08734284323967653),
 ('An animal looking at a camera.', 0.08268626849500588),
 ('A red deer foraging in sunny weather.', 0.04824744494290867),
 ('An animal reacting to a camera in clear or sunny weather.',
  0.04791212708004902),
 ('An animal reacting to a camera.', 0.04194701352834021),
 ('An animal being vigilant while the weather is rainy or overcast.',
  0.03840511743313904),
 ('An adult male red deer being vigilant after vocalizing.',
  0.028099841558616),
 ('A video of three or more red deer.', 0.01828754131871068),
 ('Two or more red deer foraging, with at least one also being vigilant at some point.',
  0.016838163088121187),
 ('An empty video.', 0.011670925805976987),
 ('A roe deer foraging in sunny weather.', 0.011104517507187496),
 ('A wolf chasing prey in clear or sunny weather.', 0.008723481686040289),
 ('A video of two adult female red deer walking while foraging.',
  0.008130699446340216),
 ('A wolf chasing prey in overcast or rainy weather.', 0.006438923395445134),
 ('A video showing individuals from at least two different species.',
  0.004883357383357384),
 ('A roe deer foraging in rainy weather.', 0.004873691465597982),
 ('An animal reacting to a camera and then foraging.', 0.004640991980524315),
 ('A video of two or more juvenile red deer.', 0.004244482173174873),
 ('An animal foraging, then reacting to a camera, and then returning to foraging.',
  0.003937284272632546),
 ('An animal escaping from another animal of the same species that is chasing it.',
  0.0037723292918050884),
 ('An adult male red deer reacting to a camera.', 0.003300905297789592),
 ('A video of two or more red deer escaping.', 0.0032992372076567863),
 ('An animal escaping from another animal of a different species that is chasing it.',
  0.0030683760683760685),
 ('An animal reacting to a camera in rainy or overcast weather.',
  0.00294194674110644),
 ('A juvenile red deer nursing.', 0.0027470727206884062),
 ('An adult female red deer nursing.', 0.0027427505674065236),
 ('A juvenile deer reacting to a camera.', 0.0023290519877675843),
 ('An animal foraging, then reacting to a camera, and then running away.',
  0.002104236258576664),
 ('An adult roe deer reacting to a camera.', 0.0020242914979757085),
 ('A juvenile red deer suckling.', 0.0018975332068311196),
 ('A juvenile red deer walking while being vigilant.', 0.0018587360594795538),
 ('A video of two or more wolves.', 0.001375515818431912)]

# mIoU and F1-score (require threshold)

Find the optimal threshold per query on train set

In [8]:
gt_json_train = Path("../zero_shot/GRAM/dataset/train/ground_truth.json")
output_folder_train = Path("/media/eceo_scratch_haas001/results/GRAM/train")
with open(gt_json_train, "r") as f:
    gt_queries_videos_train = json.load(f)
queries = gt_queries_videos_train.keys()
sim_matrix_train_df = pd.read_csv(output_folder_train / "similarity_matrix.csv").set_index("video_id")
sim_matrix_train_df

,An animal engaged in any activity other than foraging.,An animal that is neither a red deer nor a roe deer.,An animal running.,An animal bathing.,A roe deer grazing.,An animal browsing.,An adult roe deer sniffing.,A juvenile red deer scratching its body.,A chamois trotting.,An adult male roe deer jumping.,...,An animal looking at a camera.,A wolf reacting to a camera.,An animal reacting to a camera and then foraging.,"An animal foraging, then reacting to a camera, and then returning to foraging.",An animal reacting to a camera and then running away.,"An animal foraging, then reacting to a camera, and then running away.",An animal reacting to a camera in rainy or overcast weather.,An animal reacting to a camera in clear or sunny weather.,A single adult red deer foraging only.,An empty video.
video_id,,,,,,,,,,,,,,,,,,,,,
S1_C1_E104_V0262,-0.951993,-0.935011,-0.960021,-0.982698,-0.875153,-0.947459,-0.852060,-0.870437,-0.981917,-0.886899,...,-0.950602,-0.905825,-0.906353,-0.900258,-0.921213,-0.886798,-0.942923,-0.951831,-0.866776,-0.970270
S1_C1_E104_V0263,-0.953082,-0.934151,-0.961185,-0.982707,-0.877804,-0.947804,-0.855765,-0.873045,-0.980278,-0.888945,...,-0.951613,-0.910986,-0.910429,-0.904818,-0.925260,-0.893114,-0.945003,-0.953304,-0.869040,-0.969564
S1_C1_E104_V0264,-0.950579,-0.932802,-0.957093,-0.979251,-0.875009,-0.947375,-0.853505,-0.869362,-0.979612,-0.888382,...,-0.950177,-0.908023,-0.907578,-0.900658,-0.919520,-0.886936,-0.943772,-0.952103,-0.864502,-0.972996
S1_C1_E104_V0265,-0.952335,-0.932717,-0.952534,-0.980313,-0.868524,-0.945267,-0.848227,-0.864393,-0.978001,-0.882863,...,-0.946906,-0.907029,-0.909311,-0.903257,-0.920518,-0.888197,-0.944092,-0.952803,-0.863225,-0.973457
S1_C1_E104_V0266,-0.953372,-0.935144,-0.952731,-0.978695,-0.870270,-0.947068,-0.851168,-0.864713,-0.980280,-0.883223,...,-0.948637,-0.905892,-0.910089,-0.904461,-0.916945,-0.887371,-0.944615,-0.952314,-0.864791,-0.973354
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
S3_C5_F746_V0161,-0.956441,-0.930662,-0.946200,-0.982033,-0.887821,-0.942825,-0.855630,-0.863984,-0.975855,-0.879179,...,-0.939019,-0.891121,-0.906302,-0.903035,-0.900977,-0.878704,-0.937924,-0.945136,-0.879239,-0.978723
S3_C5_F760_V0162,-0.974048,-0.980564,-0.968489,-0.990404,-0.943940,-0.985698,-0.946642,-0.954286,-0.988044,-0.937009,...,-0.983129,-0.947027,-0.964362,-0.956218,-0.960842,-0.945139,-0.961564,-0.967684,-0.940488,-0.969211
S3_C5_F869_V0182,-0.986137,-0.991208,-0.978387,-0.997409,-0.963795,-0.990765,-0.972850,-0.976405,-0.992647,-0.959840,...,-0.990823,-0.974650,-0.986808,-0.980218,-0.985338,-0.976407,-0.993493,-0.985221,-0.968040,-0.974376
S3_C6_F633_V0019,-0.958188,-0.936766,-0.946992,-0.986778,-0.887120,-0.947508,-0.859842,-0.872138,-0.976808,-0.880964,...,-0.947957,-0.895569,-0.915599,-0.911687,-0.915325,-0.889595,-0.948163,-0.955943,-0.875535,-0.970287
S3_C6_F633_V0020,-0.958237,-0.940017,-0.947423,-0.984079,-0.894664,-0.949293,-0.870232,-0.877816,-0.980783,-0.888210,...,-0.945611,-0.885805,-0.914382,-0.911389,-0.908399,-0.885118,-0.945125,-0.955676,-0.886079,-0.976524

In [10]:
thrs = np.arange(sim_matrix_train_df.values.min(), sim_matrix_train_df.values.max(), step=0.01)
print("Trying thresholds:", thrs)
best_t = dict.fromkeys(gt_queries_videos_train.keys())
for q in gt_queries_videos_train.keys():
    best_IoU = 0
    if q not in sim_matrix_train_df.columns:
        print(f"Query {q} has not been processed")
        continue
    gt_videos_q = list(gt_queries_videos_train[q]["videos"])
    for t in thrs:
        ass_videos_q = list(sim_matrix_train_df.index[sim_matrix_train_df[q] > t])
        iou = IoU_q(gt_videos_q, ass_videos_q)
        if not np.isnan(iou) and iou > best_IoU:
            best_IoU = iou
            best_t[q] = t
    
    if best_t[q] is None:
        print(f"No best threshold found for {q}, using median similarity score as threshold")
        best_t[q] = np.median(sim_matrix_train_df.values)

Trying thresholds: [-0.99985766 -0.98985766 -0.97985766 -0.96985766 -0.95985766 -0.94985766
 -0.93985766 -0.92985766 -0.91985766 -0.90985766 -0.89985766 -0.88985766
 -0.87985766 -0.86985766 -0.85985766 -0.84985766 -0.83985766 -0.82985766
 -0.81985766 -0.80985766 -0.79985766]

In [11]:
mF1, F1_queries = F1_score_from_sim(gt_queries_videos=gt_queries_videos, sim_matrix_df=sim_matrix_df, best_thresholds=best_t)
mIoU, IoU_queries = IoU_from_sim(gt_queries_videos=gt_queries_videos, sim_matrix_df=sim_matrix_df, best_thresholds=best_t)

In [12]:
print(f"F1-score (macro-avg.): {mF1:.2f}")
print(f"mean IoU: {mIoU:.2f}")

F1-score (macro-avg.): 0.04
mean IoU: 0.02

In [13]:
results_df = pd.concat([
    pd.DataFrame.from_dict(IoU_queries, orient="index", columns=["mIoU"]),
    pd.DataFrame.from_dict(F1_queries, orient="index", columns=["F1-score"])
], axis=1)

pd.set_option('display.max_rows', 100)
pd.set_option('display.max_colwidth', 90)
results_df.sort_values("mIoU", ascending=False)

,mIoU,F1-score
A single adult red deer foraging only.,0.372654,0.542969
An animal engaged in any activity other than foraging.,0.204724,0.339869
An adult female red deer foraging and a juvenile red deer foraging.,0.134228,0.236686
A video of two red deer.,0.121795,0.217143
Rainy weather.,0.096059,0.175281
An animal being vigilant while the weather is clear or sunny.,0.093791,0.171498
A video of two or more animals.,0.092328,0.169048
A video of an individual sniffing while reacting to a camera.,0.090909,0.166667
A video of an animal lying down while resting.,0.075949,0.141176
A red deer foraging in sunny weather.,0.068627,0.128440
An animal running.,0.067602,0.126643
A juvenile deer in clear or sunny weather.,0.060523,0.114137
A juvenile red deer doing the exact same activities as an adult female red deer.,0.056680,0.107280
A red deer foraging in rainy weather.,0.050420,0.096000
An animal being vigilant while the weather is rainy or overcast.,0.050000,0.095238
An animal resting.,0.041096,0.078947
A juvenile red deer doing at least one different action than an adult female red deer.,0.039735,0.076433
An animal running while foraging.,0.037185,0.071703
An animal reacting to a camera and then running away.,0.033333,0.064516
An adult male red deer rubbing its antlers on the ground.,0.032609,0.063158
A juvenile red deer doing the exact same actions as an adult female red deer.,0.030172,0.058577
An adult red deer vocalizing while participating in courtship.,0.029126,0.056604
An animal participating in courtship.,0.028025,0.054523
An adult male red deer being vigilant after vocalizing.,0.027027,0.052632
An animal that is neither a red deer nor a roe deer.,0.026954,0.052493
An adult male red deer pawing the ground and rubbing its antlers on the ground while wallowing.,0.026490,0.051613
An animal bathing.,0.021978,0.043011
An adult female red deer reacting to a camera.,0.020619,0.040404
An adult red deer standing with its head up while participating in courtship.,0.020202,0.039604
An adult male red deer pawing the ground while wallowing.,0.018100,0.035556
An adult red deer reacting to a camera.,0.015748,0.031008
An animal running while reacting to a camera.,0.013514,0.026667
An animal reacting to a camera in clear or sunny weather.,0.013333,0.026316
A video of two adult female red deer walking while foraging.,0.012179,0.024064
A video of three or more red deer.,0.011765,0.023256
A red deer browsing.,0.011364,0.022472
A roe deer trotting while foraging.,0.008065,0.016000
A video of an animal drinking.,0.008000,0.015873
A wolf chasing prey.,0.007722,0.015326
An animal reacting to a camera.,0.006897,0.013699
A hare.,0.006757,0.013423
An animal browsing.,0.006748,0.013405
A chamois.,0.006720,0.013351
An animal looking at a camera.,0.006410,0.012739
A wolf chasing prey in overcast or rainy weather.,0.005405,0.010753
A hare foraging.,0.005398,0.010738
An animal bathing while grooming.,0.004367,0.008696
A roe deer foraging in rainy weather.,0.004317,0.008596
A wolf chasing prey in clear or sunny weather.,0.004167,0.008299
A mountain hare being vigilant.,0.004076,0.008119
A video showing individuals from at least two different species.,0.004071,0.008108
A roe deer foraging in sunny weather.,0.004038,0.008043
An animal escaping from another animal of a different species that is chasing it.,0.003534,0.007042
An adult male roe deer jumping.,0.002717,0.005420
A chamois being vigilant.,0.002706,0.005398
A chamois trotting.,0.002688,0.005362
An animal stretching its body.,0.001623,0.003241
An adult red deer browsing.,0.001585,0.003165
An adult female red deer running while participating in courtship.,0.001395,0.002786
A red deer resting in rainy weather.,0.000000,0.000000
An adult roe deer sniffing.,0.000000,0.000000
A roe deer grazing.,0.000000,0.000000
A juvenile red deer scratching its body.,0.000000,0.000000
A wolf foraging.,0.000000,0.000000
A mountain hare grazing.,0.000000,0.000000
A marten.,0.000000,0.000000
A juvenile red deer playing.,0.000000,0.000000
A fox foraging.,0.000000,0.000000
A juvenile deer in rainy weather.,0.000000,0.000000
A red deer resting in clear weather.,0.000000,0.000000
A video of two or more juvenile red deer.,0.000000,0.000000
An animal escaping from another animal of the same species that is chasing it.,0.000000,0.000000
A video of two or more wolves.,0.000000,0.000000
A red deer participating in courtship in rainy weather.,0.000000,0.000000
A video of two or more red deer escaping.,0.000000,0.000000
A juvenile red deer walking while being vigilant.,0.000000,0.000000
A roe deer participating in courtship in clear weather.,0.000000,0.000000
A video of one adult male and one adult female red deer running while participating in courtship.,0.000000,0.000000
An adult male red deer running while participating in courtship.,0.000000,0.000000
A video of one adult male and one adult female roe deer running while participating in courtship.,0.000000,0.000000
An adult female roe deer running while participating in courtship.,0.000000,0.000000
An adult male red deer bathing while wallowing.,0.000000,0.000000
An adult male red deer urinating while wallowing.,0.000000,0.000000
A red deer vocalizing in rainy weather.,0.000000,0.000000
An adult red deer lying down while participating in courtship.,0.000000,0.000000
An adult male roe deer running while participating in courtship.,0.000000,0.000000
A juvenile red deer suckling.,0.000000,0.000000
A juvenile red deer nursing.,0.000000,0.000000
An adult roe deer reacting to a camera.,0.000000,0.000000
Two or more animals reacting to a camera.,0.000000,0.000000
"Two or more red deer foraging, with at least one also being vigilant at some point.",0.000000,0.000000
An adult female red deer nursing.,0.000000,0.000000
A juvenile deer reacting to a camera.,0.000000,0.000000
A video of three or more red deer reacting to a camera.,0.000000,0.000000
An adult male red deer reacting to a camera.,0.000000,0.000000
An animal reacting to a camera and then foraging.,0.000000,0.000000
"An animal foraging, then reacting to a camera, and then running away.",0.000000,0.000000
"An animal foraging, then reacting to a camera, and then returning to foraging.",0.000000,0.000000
An animal reacting to a camera in rainy or overcast weather.,0.000000,0.000000
An empty video.,0.000000,0.000000