In [6]:
import json
from pathlib import Path
import pandas as pd
import numpy as np

from metrics import (
    F1_score,
    IoU,
)

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [11]:
gt_videos_path = Path(
    "../benchmark/queries_and_videos_test.json"
)

all_possible_videos = list([f.stem for f in Path(
    "/media/EVO870/datasets/prompting-mammalps-v2/annotations_2023/test"
).rglob("*.json")])

retrieved_results_path = Path(
    "/media/eceo_scratch_haas001/results/prompting_mammalps-v2/LLM/qwen/Qwen3-8B-oracle_2023_orig.json"
)  # Path to the JSON file create by run.py

with open(gt_videos_path, "r") as f:
    gt_videos_cat = json.load(f)

gt_videos = {}
for cat in gt_videos_cat:
    
    for query, video_list  in gt_videos_cat[cat].items():
        gt_videos[query] = video_list

with open(retrieved_results_path, "r") as f:
    pred_videos = json.load(f)


with open("../benchmark/query_categories.json", "r") as f:
    query_categories = json.load(f)

query2eco_cat = {q: [] for q in gt_videos.keys()}
for cat in query_categories["ECOLOGY"]:
    for q in query_categories["ECOLOGY"][cat]:
        query2eco_cat[q].append(cat)

query2cv_cat = {q: [] for q in gt_videos.keys()}
for cat in query_categories["VISION"]:
    for q in query_categories["VISION"][cat]:
        query2cv_cat[q].append(cat)

# Overall performance

In [12]:
mF1, F1_queries = F1_score(gt_queries_videos=gt_videos, pred_queries_videos=pred_videos, all_videos=all_possible_videos)
mIoU, IoU_queries = IoU(gt_queries_videos=gt_videos, pred_queries_videos=pred_videos, all_videos=all_possible_videos)

In [13]:
print(f"F1-score (macro-avg.): {mF1:.2f}")
print(f"mean IoU: {mIoU:.2f}")

F1-score (macro-avg.): 0.29
mean IoU: 0.24

In [14]:
print(f"F1-score (macro-avg.) w/o Ref prompts: {np.nanmean([s for q, s in F1_queries.items() if '<vid>' not in q]):.2f}")
print(f"mean IoU w/o Ref prompts : {np.nanmean([s for q, s in IoU_queries.items() if '<vid>' not in q]):.2f}")

F1-score (macro-avg.) w/o Ref prompts: 0.32
mean IoU w/o Ref prompts : 0.27

# Performance per query et per category

In [13]:
results_df = pd.concat([
    pd.DataFrame.from_dict(IoU_queries, orient="index", columns=["mIoU"]),
    pd.DataFrame.from_dict(F1_queries, orient="index", columns=["F1-score"]),
    ], axis=1)

pd.set_option('display.max_rows', 150)
pd.set_option('display.max_colwidth', 90)
results_df.sort_values("mIoU", ascending=False)

,mIoU,F1-score
A red deer participating in courtship in rainy weather.,1.000000,1.000000
A roe deer participating in courtship in rainy weather.,1.000000,1.000000
A red deer resting in rainy weather.,1.000000,1.000000
A juvenile roe deer.,1.000000,1.000000
A fox chasing prey.,1.000000,1.000000
A fox sniffing.,1.000000,1.000000
A juvenile roe deer preparing to suckle.,1.000000,1.000000
An individual doing the same sequence of actions as the individual of <vid>S2_C1_E323_V0074</vid>.,1.000000,1.000000
A fox reacting to a camera.,1.000000,1.000000
A red deer vocalizing in rainy weather.,1.000000,1.000000
A wolf reacting to a camera.,1.000000,1.000000
An adult female red deer escaping in sunny weather.,1.000000,1.000000
A fox chasing prey in clear weather.,1.000000,1.000000
A wolf chasing prey in clear or sunny weather.,1.000000,1.000000
A video of two adult red deer vocalizing while participating in courtship.,1.000000,1.000000
A video of three or more adult male red deer walking while foraging.,1.000000,1.000000
A video of two or more wolves.,1.000000,1.000000
A juvenile roe deer suckling.,1.000000,1.000000
An animal bathing while grooming.,0.750000,0.857143
A red deer resting in clear weather.,0.750000,0.857143
An individual sharing at least one activity with any individual from <vid>S3_C2_E670_V0159</vid> but in a different weather condition.,0.698113,0.822222
A video of an animal drinking.,0.666667,0.800000
An animal being vigilant while the weather is rainy or overcast.,0.619565,0.765101
An animal participating in courtship.,0.619048,0.764706
A video of three or more red deer.,0.583333,0.736842
Rainy weather.,0.555556,0.714286
An animal engaged in any activity other than foraging.,0.521008,0.685083
An animal being vigilant while the weather is clear or sunny.,0.515385,0.680203
An animal running.,0.510638,0.676056
A fox foraging.,0.500000,0.666667
A video of an animal lying down while resting.,0.500000,0.666667
An animal resting.,0.500000,0.666667
A red deer foraging in rainy weather.,0.500000,0.666667
A wolf chasing prey.,0.500000,0.666667
An animal reacting to a camera and then running away.,0.454545,0.625000
A red deer foraging in sunny weather.,0.416667,0.588235
An animal bathing.,0.400000,0.571429
An animal running while reacting to a camera.,0.363636,0.533333
A video of two or more animals.,0.340206,0.507692
A video of two or more red deer escaping.,0.300000,0.461538
An empty video.,0.297297,0.458333
An animal reacting to a camera in clear or sunny weather.,0.269231,0.424242
An animal reacting to a camera.,0.258065,0.410256
A video of two red deer.,0.250000,0.400000
An individual doing at least one different action while reacting to a camera than with any individual of <vid>S1_C3_E144_V0060</vid>.,0.238095,0.384615
An animal looking at a camera.,0.217391,0.357143
A hare.,0.200000,0.333333
A video of an individual sniffing while reacting to a camera.,0.200000,0.333333
"An animal foraging, then reacting to a camera, and then returning to foraging.",0.200000,0.333333
An animal reacting to a camera in rainy or overcast weather.,0.200000,0.333333
An individual performing the same activities as any individual from <vid>S2_C2_E351_V0099</vid> but in a different weather condition.,0.177778,0.301887
An individual sharing at least one activity with any individual from <vid>S1_C1_E66_V0152</vid> but of a different species.,0.163265,0.280702
An animal running while foraging.,0.155172,0.268657
"Two or more red deer foraging, with at least one also being vigilant at some point.",0.153846,0.266667
An animal reacting to a camera and then foraging.,0.125000,0.222222
An animal that is neither a red deer nor a roe deer.,0.113636,0.204082
An individual doing the same unique actions while reacting to a camera as any individual of <vid>S1_C3_E144_V0060</vid>.,0.111111,0.200000
A roe deer grazing.,0.090909,0.166667
An animal browsing.,0.000000,0.000000
An adult roe deer sniffing.,0.000000,0.000000
A roe deer trotting while foraging.,0.000000,0.000000
A juvenile red deer shaking its head or body.,0.000000,0.000000
A wolf foraging.,0.000000,0.000000
A red deer browsing.,0.000000,0.000000
A mountain hare being vigilant.,0.000000,0.000000
A chamois being vigilant.,0.000000,0.000000
An adult red deer browsing.,0.000000,0.000000
A marten.,0.000000,0.000000
A chamois.,0.000000,0.000000
A hare foraging.,0.000000,0.000000
An adult male roe deer jumping.,0.000000,0.000000
A video showing individuals from at least two different species.,0.000000,0.000000
An adult female red deer foraging and a juvenile red deer foraging.,0.000000,0.000000
A juvenile red deer walking while being vigilant.,0.000000,0.000000
A video of two adult female red deer walking while foraging.,0.000000,0.000000
An adult male red deer urinating while wallowing.,0.000000,0.000000
A roe deer participating in courtship in clear weather.,0.000000,0.000000
An adult male red deer being vigilant after vocalizing.,0.000000,0.000000
An adult male red deer running while participating in courtship.,0.000000,0.000000
An adult female red deer running while participating in courtship.,0.000000,0.000000
A video of one adult male and one adult female red deer running while participating in courtship.,0.000000,0.000000
An adult male roe deer running while participating in courtship.,0.000000,0.000000
An adult female roe deer running while participating in courtship.,0.000000,0.000000
A video of one adult male and one adult female roe deer running while participating in courtship.,0.000000,0.000000
An adult male red deer pawing the ground while wallowing.,0.000000,0.000000
An adult male red deer pawing the ground and rubbing its antlers on the ground while wallowing.,0.000000,0.000000
An adult male red deer bathing while wallowing.,0.000000,0.000000
A juvenile deer in clear or sunny weather.,0.000000,0.000000
An adult red deer lying down while participating in courtship.,0.000000,0.000000
An adult red deer vocalizing while participating in courtship.,0.000000,0.000000
An adult red deer standing with its head up while participating in courtship.,0.000000,0.000000
A juvenile deer in rainy weather.,0.000000,0.000000
A juvenile red deer playing.,0.000000,0.000000
A juvenile red deer scratching its body.,0.000000,0.000000
An adult male red deer rubbing its antlers on the ground.,0.000000,0.000000
A chamois trotting.,0.000000,0.000000
A mountain hare grazing.,0.000000,0.000000
An animal stretching its body.,0.000000,0.000000
A wolf chasing prey in overcast or rainy weather.,0.000000,0.000000
A roe deer foraging in sunny weather.,0.000000,0.000000
An animal escaping from another animal of the same species that is chasing it.,0.000000,0.000000
A juvenile red deer suckling.,0.000000,0.000000
A juvenile red deer nursing.,0.000000,0.000000
An adult female red deer reacting to a camera.,0.000000,0.000000
An adult red deer reacting to a camera.,0.000000,0.000000
A juvenile deer reacting to a camera.,0.000000,0.000000
An adult male red deer reacting to a camera.,0.000000,0.000000
A video of three or more red deer reacting to a camera.,0.000000,0.000000
A roe deer foraging in rainy weather.,0.000000,0.000000
Two or more animals reacting to a camera.,0.000000,0.000000
An adult roe deer reacting to a camera.,0.000000,0.000000
A juvenile red deer doing the exact same activities as an adult female red deer.,0.000000,0.000000
A video of two or more juvenile red deer.,0.000000,0.000000
An animal escaping from another animal of a different species that is chasing it.,0.000000,0.000000
A juvenile red deer doing the exact same actions as an adult female red deer.,0.000000,0.000000
An adult female red deer nursing.,0.000000,0.000000
A juvenile red deer doing at least one different action than an adult female red deer.,0.000000,0.000000
An adult male red deer doing the same sequence of actions while wallowing as any individual of <vid>S3_C2_E769_V0436</vid>.,0.000000,0.000000
"An animal foraging, then reacting to a camera, and then running away.",0.000000,0.000000
A juvenile red deer performing at least one different action while nursing than with any individual in <vid>S1_C6_F404_V0330</vid>.,0.000000,0.000000
A juvenile red deer performing at least one action in common while nursing with any individual in <vid>S1_C6_F404_V0330</vid>.,0.000000,0.000000
A juvenile red deer performing at least one action in common while nursing with any individual in <vid>S1_C6_F394_V0310</vid>.,0.000000,0.000000
An adult male red deer performing at least one different action while wallowing than with any individual of <vid>S3_C3_E524_V0327</vid>.,0.000000,0.000000
An adult male red deer doing the same unique actions while wallowing as any individual of <vid>S3_C2_E524_V0087</vid>.,0.000000,0.000000
An adult male red deer doing the same unique actions while wallowing as any individual of <vid>S3_C3_E524_V0327</vid>.,0.000000,0.000000
An adult male red deer doing the same sequence of actions while wallowing as any individual of <vid>S3_C3_E524_V0327</vid>.,0.000000,0.000000
An individual doing the same sequence of actions while reacting to a camera as any individual of <vid>S1_C4_F173_V0137</vid>.,0.000000,0.000000
An animal being vigilant in a different weather condition from that in <vid>S2_C2_F536_V0066</vid>.,0.000000,0.000000
An individual doing at least one different action while reacting to a camera than with any individual of <vid>S1_C4_F173_V0137</vid>.,0.000000,0.000000
An individual doing the same sequence of actions while reacting to a camera as any individual of <vid>S1_C3_E144_V0060</vid>.,0.000000,0.000000
An individual doing the same unique actions while reacting to a camera as any individual of <vid>S1_C4_F173_V0137</vid>.,0.000000,0.000000
An individual sharing at least one activity with any individual of the same species from <vid>S1_C4_F136_V0115</vid> but in a different weather condition.,0.000000,0.000000
An individual sharing at least one activity with any individual from <vid>S2_C1_F573_V0093</vid>.,0.000000,0.000000
A wolf chasing prey in a different weather condition from that in <vid>S2_C1_F573_V0093</vid>.,0.000000,0.000000
A single adult red deer foraging only.,0.000000,0.000000

In [14]:
len(results_df[results_df[["F1-score"]]==0])

135

In [52]:
eco_cat_df = pd.DataFrame([query2eco_cat], index=["eco_cat"]).T
cv_cat_df = pd.DataFrame([query2cv_cat], index=["cv_cat"]).T
results_cat_df = results_df.merge(eco_cat_df, left_index=True, right_index=True).merge(cv_cat_df, left_index=True, right_index=True)

In [53]:
# Ecology categories
results_cat_df[["mIoU", "F1-score", "eco_cat"]].explode(["eco_cat"]).groupby("eco_cat").mean().T

eco_cat   CAMERA_REACTION    COMMON  COURTSHIP      RARE    SOCIAL
mIoU             0.147499  0.759409   0.248798  0.343454  0.286984
F1-score         0.190382  0.858781   0.311536  0.427785  0.330484

In [54]:
results_cat_df[["mIoU", "F1-score", "eco_cat"]].explode(["eco_cat"]).groupby("eco_cat").count().T

eco_cat   CAMERA_REACTION  COMMON  COURTSHIP  RARE  SOCIAL
mIoU                   28       2         27    48      36
F1-score               28       2         27    48      36

In [55]:
results_cat_df[["mIoU", "F1-score", "cv_cat"]].explode(["cv_cat"]).groupby("cv_cat").mean().T

cv_cat     COMPLEX  MULTI_ATTR  MULTI_INDIV  SINGLE_ATTR  VIDEO_COMPARISON
mIoU      0.172718    0.306205     0.146442     0.264859          0.086783
F1-score  0.216052    0.371186     0.188554     0.353194          0.130371

In [56]:
results_cat_df[["mIoU", "F1-score", "cv_cat"]].explode(["cv_cat"]).groupby("cv_cat").count().T

cv_cat    COMPLEX  MULTI_ATTR  MULTI_INDIV  SINGLE_ATTR  VIDEO_COMPARISON
mIoU           15          92           25           14                22
F1-score       15          92           25           14                22

## Individual query

In [30]:
print("def check_file(file_id):\n    individual_tracks = get_tracks_from_file_id(file_id)\n    has_adult_red_deer = check_tracks_contain_deer_age(individual_tracks, age=DAge.ADULT, deer_species=Species.RED_DEER)\n    if not has_adult_red_deer:\n        return False\n    unique_activities = get_unique_activities_from_tracks(individual_tracks)\n    return unique_activities == {Activity.FORAGING}")

def check_file(file_id):
    individual_tracks = get_tracks_from_file_id(file_id)
    has_adult_red_deer = check_tracks_contain_deer_age(individual_tracks, age=DAge.ADULT, deer_species=Species.RED_DEER)
    if not has_adult_red_deer:
        return False
    unique_activities = get_unique_activities_from_tracks(individual_tracks)
    return unique_activities == {Activity.FORAGING}

In [32]:
q = "A single adult red deer foraging only."
print("Size of retrieved set", len(pred_videos[q]))
print("Size of GT set", len(gt_videos[q]))
print("True positives", len(set(pred_videos[q]).intersection(set(gt_videos[q]))))
print("Missing videos", len(set(gt_videos[q]) - set(pred_videos[q])))
print("false positives", len(set(pred_videos[q]) - set(gt_videos[q])))
print("True negatives", len((set(all_possible_videos) - set(gt_videos[q])).intersection(set(all_possible_videos) - set(pred_videos[q]))))

Size of retrieved set 356
Size of GT set 373
True positives 292
Missing videos 81
false positives 64
True negatives 338

In [33]:
print("Missing videos:")
set(gt_videos[q]) - set(pred_videos[q])

Missing videos:

{'S1_C1_E117_V0360',
 'S1_C2_E121_V0187',
 'S1_C2_E121_V0192',
 'S1_C2_E121_V0193',
 'S1_C2_E143_V0327',
 'S1_C2_E144_V0328',
 'S1_C2_E196_V0443',
 'S1_C4_F269_V0273',
 'S1_C4_F269_V0274',
 'S1_C4_F269_V0275',
 'S1_C4_F270_V0278',
 'S1_C4_F270_V0279',
 'S1_C4_F270_V0280',
 'S1_C4_F270_V0281',
 'S1_C4_F270_V0282',
 'S1_C4_F270_V0283',
 'S1_C4_F270_V0284',
 'S1_C4_F270_V0285',
 'S1_C4_F270_V0286',
 'S1_C4_F270_V0290',
 'S1_C4_F287_V0306',
 'S1_C4_F288_V0315',
 'S1_C4_F288_V0375',
 'S1_C4_F290_V0377',
 'S1_C6_F167_V0096',
 'S1_C6_F268_V0179',
 'S1_C6_F287_V0207',
 'S1_C6_F288_V0210',
 'S1_C6_F288_V0211',
 'S1_C6_F288_V0212',
 'S1_C6_F288_V0215',
 'S1_C6_F288_V0216',
 'S1_C6_F288_V0223',
 'S1_C6_F288_V0225',
 'S1_C6_F288_V0226',
 'S1_C6_F288_V0227',
 'S1_C6_F288_V0229',
 'S1_C6_F288_V0241',
 'S1_C6_F289_V0247',
 'S1_C6_F289_V0248',
 'S1_C6_F289_V0249',
 'S1_C6_F289_V0253',
 'S1_C6_F394_V0312',
 'S1_C6_F405_V0357',
 'S1_C6_F405_V0358',
 'S1_C6_F405_V0360',
 'S2_C1_E359_V0095',
 'S2_C1_E376_V0107',
 'S2_C2_E349_V0094',
 'S2_C2_E359_V0106',
 'S2_C2_E370_V0115',
 'S2_C2_E371_V0116',
 'S2_C2_F494_V0047',
 'S2_C3_E371_V0119',
 'S2_C3_E376_V0124',
 'S3_C2_E616_V0126',
 'S3_C2_E616_V0127',
 'S3_C2_E616_V0128',
 'S3_C2_E638_V0138',
 'S3_C2_E639_V0141',
 'S3_C2_E671_V0165',
 'S3_C2_E671_V0167',
 'S3_C2_E718_V0268',
 'S3_C2_E719_V0269',
 'S3_C2_E719_V0271',
 'S3_C2_E719_V0276',
 'S3_C2_E720_V0278',
 'S3_C2_E721_V0279',
 'S3_C2_E723_V0282',
 'S3_C2_E723_V0287',
 'S3_C2_E723_V0290',
 'S3_C2_E725_V0307',
 'S3_C2_E735_V0344',
 'S3_C2_E735_V0349',
 'S3_C2_E736_V0351',
 'S3_C2_E736_V0354',
 'S3_C2_E769_V0441',
 'S3_C2_E790_V0514',
 'S3_C2_E791_V0516',
 'S3_C4_F720_V0081',
 'S3_C4_F720_V0090'}

In [34]:
print("False positives")

set(pred_videos[q]) - set(gt_videos[q])

False positives

{'S1_C1_E117_V0365',
 'S1_C1_E139_V0706',
 'S1_C1_E60_V0143',
 'S1_C1_E60_V0144',
 'S1_C2_E118_V0181',
 'S1_C3_E200_V0084',
 'S1_C4_F269_V0260',
 'S1_C4_F269_V0261',
 'S1_C4_F269_V0262',
 'S1_C4_F269_V0263',
 'S1_C4_F269_V0264',
 'S1_C4_F269_V0265',
 'S1_C4_F269_V0268',
 'S1_C4_F288_V0309',
 'S1_C4_F288_V0374',
 'S1_C5_F172_V0227',
 'S1_C5_F267_V0428',
 'S1_C6_F175_V0102',
 'S1_C6_F179_V0104',
 'S1_C6_F269_V0182',
 'S1_C6_F269_V0185',
 'S1_C6_F269_V0187',
 'S1_C6_F289_V0256',
 'S1_C6_F393_V0305',
 'S1_C6_F394_V0310',
 'S1_C6_F394_V0315',
 'S1_C6_F394_V0319',
 'S1_C6_F394_V0323',
 'S1_C6_F404_V0331',
 'S1_C6_F404_V0332',
 'S1_C6_F404_V0333',
 'S1_C6_F404_V0334',
 'S1_C6_F404_V0335',
 'S1_C6_F404_V0336',
 'S1_C6_F404_V0337',
 'S1_C6_F404_V0338',
 'S1_C6_F404_V0339',
 'S1_C6_F404_V0340',
 'S1_C6_F404_V0341',
 'S1_C6_F404_V0346',
 'S1_C6_F405_V0362',
 'S2_C1_E284_V0040',
 'S2_C1_E291_V0043',
 'S2_C1_E323_V0074',
 'S2_C1_E353_V0087',
 'S2_C1_E353_V0090',
 'S2_C1_E358_V0094',
 'S2_C1_F492_V0040',
 'S2_C2_E293_V0046',
 'S2_C2_E297_V0048',
 'S2_C2_E332_V0079',
 'S2_C2_E351_V0099',
 'S2_C2_E369_V0114',
 'S2_C3_E323_V0090',
 'S2_C3_E374_V0122',
 'S2_C3_F497_V0072',
 'S2_C3_F537_V0096',
 'S3_C2_E723_V0293',
 'S3_C2_E723_V0294',
 'S3_C2_E723_V0295',
 'S3_C2_E723_V0302',
 'S3_C2_E725_V0310',
 'S3_C2_E764_V0423',
 'S3_C2_E769_V0439'}

In [35]:
print("Correctly retrieved")
set(pred_videos[q]).intersection(set(gt_videos[q]))

Correctly retrieved

{'S1_C1_E103_V0254',
 'S1_C1_E103_V0255',
 'S1_C1_E103_V0256',
 'S1_C1_E103_V0257',
 'S1_C1_E103_V0258',
 'S1_C1_E103_V0259',
 'S1_C1_E103_V0260',
 'S1_C1_E103_V0261',
 'S1_C1_E117_V0359',
 'S1_C1_E117_V0361',
 'S1_C1_E117_V0362',
 'S1_C1_E117_V0363',
 'S1_C1_E117_V0364',
 'S1_C1_E117_V0366',
 'S1_C1_E117_V0367',
 'S1_C1_E117_V0368',
 'S1_C1_E117_V0369',
 'S1_C1_E117_V0370',
 'S1_C1_E117_V0371',
 'S1_C1_E117_V0372',
 'S1_C1_E117_V0373',
 'S1_C1_E117_V0374',
 'S1_C1_E118_V0375',
 'S1_C1_E118_V0376',
 'S1_C1_E118_V0380',
 'S1_C1_E118_V0385',
 'S1_C1_E118_V0388',
 'S1_C1_E118_V0389',
 'S1_C1_E121_V0402',
 'S1_C1_E121_V0403',
 'S1_C1_E121_V0404',
 'S1_C1_E121_V0405',
 'S1_C1_E121_V0406',
 'S1_C1_E121_V0408',
 'S1_C1_E121_V0409',
 'S1_C1_E121_V0410',
 'S1_C1_E121_V0411',
 'S1_C1_E121_V0412',
 'S1_C1_E121_V0413',
 'S1_C1_E121_V0414',
 'S1_C1_E121_V0415',
 'S1_C1_E121_V0416',
 'S1_C1_E121_V0417',
 'S1_C1_E121_V0418',
 'S1_C1_E121_V0419',
 'S1_C1_E121_V0421',
 'S1_C1_E121_V0422',
 'S1_C1_E121_V0425',
 'S1_C1_E121_V0426',
 'S1_C1_E121_V0427',
 'S1_C1_E121_V0428',
 'S1_C1_E121_V0430',
 'S1_C1_E121_V0432',
 'S1_C1_E121_V0433',
 'S1_C1_E121_V0435',
 'S1_C1_E121_V0438',
 'S1_C1_E121_V0440',
 'S1_C1_E121_V0441',
 'S1_C1_E121_V0448',
 'S1_C1_E142_V0707',
 'S1_C1_E142_V0708',
 'S1_C1_E143_V0710',
 'S1_C1_E143_V0711',
 'S1_C1_E143_V0713',
 'S1_C1_E143_V0716',
 'S1_C1_E143_V0717',
 'S1_C1_E143_V0718',
 'S1_C1_E143_V0720',
 'S1_C1_E143_V0721',
 'S1_C1_E143_V0722',
 'S1_C1_E143_V0723',
 'S1_C1_E194_V0835',
 'S1_C1_E98_V0221',
 'S1_C1_E98_V0222',
 'S1_C1_E98_V0223',
 'S1_C1_E98_V0224',
 'S1_C1_E98_V0225',
 'S1_C1_E98_V0226',
 'S1_C1_E98_V0227',
 'S1_C1_E98_V0228',
 'S1_C1_E98_V0229',
 'S1_C1_E98_V0230',
 'S1_C1_E98_V0231',
 'S1_C1_E98_V0232',
 'S1_C1_E98_V0233',
 'S1_C1_E98_V0234',
 'S1_C1_E98_V0235',
 'S1_C1_E98_V0236',
 'S1_C1_E98_V0237',
 'S1_C1_E98_V0238',
 'S1_C1_E98_V0240',
 'S1_C2_E117_V0170',
 'S1_C2_E117_V0171',
 'S1_C2_E117_V0172',
 'S1_C2_E117_V0173',
 'S1_C2_E117_V0174',
 'S1_C2_E117_V0175',
 'S1_C2_E117_V0176',
 'S1_C2_E117_V0177',
 'S1_C2_E118_V0180',
 'S1_C2_E118_V0182',
 'S1_C2_E118_V0183',
 'S1_C2_E121_V0185',
 'S1_C2_E121_V0186',
 'S1_C2_E121_V0188',
 'S1_C2_E121_V0190',
 'S1_C2_E121_V0191',
 'S1_C2_E143_V0320',
 'S1_C2_E143_V0321',
 'S1_C2_E143_V0322',
 'S1_C2_E143_V0324',
 'S1_C2_E143_V0325',
 'S1_C2_E143_V0326',
 'S1_C2_E196_V0445',
 'S1_C2_E196_V0447',
 'S1_C2_E197_V0453',
 'S1_C2_E197_V0454',
 'S1_C2_E197_V0455',
 'S1_C2_E197_V0456',
 'S1_C2_E197_V0458',
 'S1_C2_E197_V0459',
 'S1_C2_E197_V0462',
 'S1_C2_E198_V0469',
 'S1_C2_E198_V0470',
 'S1_C2_E198_V0480',
 'S1_C2_E198_V0482',
 'S1_C4_F269_V0259',
 'S1_C4_F269_V0271',
 'S1_C4_F269_V0272',
 'S1_C4_F270_V0287',
 'S1_C4_F270_V0289',
 'S1_C4_F287_V0304',
 'S1_C4_F288_V0308',
 'S1_C4_F288_V0310',
 'S1_C4_F288_V0311',
 'S1_C4_F288_V0312',
 'S1_C4_F288_V0313',
 'S1_C4_F288_V0314',
 'S1_C4_F288_V0316',
 'S1_C4_F288_V0317',
 'S1_C4_F288_V0318',
 'S1_C4_F288_V0319',
 'S1_C4_F288_V0320',
 'S1_C4_F288_V0321',
 'S1_C4_F288_V0322',
 'S1_C4_F288_V0323',
 'S1_C4_F288_V0325',
 'S1_C4_F288_V0326',
 'S1_C4_F288_V0327',
 'S1_C4_F288_V0328',
 'S1_C4_F288_V0329',
 'S1_C4_F288_V0330',
 'S1_C4_F288_V0331',
 'S1_C4_F288_V0332',
 'S1_C4_F288_V0333',
 'S1_C4_F288_V0334',
 'S1_C4_F288_V0335',
 'S1_C4_F288_V0336',
 'S1_C4_F288_V0337',
 'S1_C4_F288_V0338',
 'S1_C4_F288_V0339',
 'S1_C4_F288_V0340',
 'S1_C4_F288_V0341',
 'S1_C4_F288_V0342',
 'S1_C4_F288_V0343',
 'S1_C4_F288_V0345',
 'S1_C4_F288_V0347',
 'S1_C4_F288_V0348',
 'S1_C4_F288_V0351',
 'S1_C4_F288_V0352',
 'S1_C4_F288_V0353',
 'S1_C4_F288_V0354',
 'S1_C4_F288_V0355',
 'S1_C4_F288_V0358',
 'S1_C4_F288_V0360',
 'S1_C4_F288_V0361',
 'S1_C4_F288_V0362',
 'S1_C4_F288_V0363',
 'S1_C4_F288_V0364',
 'S1_C4_F288_V0365',
 'S1_C4_F288_V0366',
 'S1_C4_F288_V0368',
 'S1_C4_F288_V0370',
 'S1_C4_F288_V0371',
 'S1_C4_F288_V0372',
 'S1_C4_F288_V0373',
 'S1_C4_F288_V0376',
 'S1_C4_F393_V0450',
 'S1_C5_F170_V0224',
 'S1_C5_F179_V0230',
 'S1_C6_F269_V0181',
 'S1_C6_F269_V0186',
 'S1_C6_F269_V0188',
 'S1_C6_F269_V0189',
 'S1_C6_F269_V0190',
 'S1_C6_F269_V0191',
 'S1_C6_F270_V0194',
 'S1_C6_F270_V0195',
 'S1_C6_F270_V0196',
 'S1_C6_F270_V0197',
 'S1_C6_F270_V0198',
 'S1_C6_F270_V0199',
 'S1_C6_F270_V0200',
 'S1_C6_F287_V0206',
 'S1_C6_F287_V0208',
 'S1_C6_F288_V0209',
 'S1_C6_F288_V0213',
 'S1_C6_F288_V0217',
 'S1_C6_F288_V0218',
 'S1_C6_F288_V0219',
 'S1_C6_F288_V0220',
 'S1_C6_F288_V0221',
 'S1_C6_F288_V0222',
 'S1_C6_F288_V0224',
 'S1_C6_F288_V0228',
 'S1_C6_F288_V0230',
 'S1_C6_F288_V0231',
 'S1_C6_F288_V0232',
 'S1_C6_F288_V0233',
 'S1_C6_F288_V0234',
 'S1_C6_F288_V0235',
 'S1_C6_F288_V0236',
 'S1_C6_F288_V0239',
 'S1_C6_F288_V0240',
 'S1_C6_F288_V0242',
 'S1_C6_F288_V0243',
 'S1_C6_F288_V0244',
 'S1_C6_F288_V0245',
 'S1_C6_F288_V0246',
 'S1_C6_F289_V0250',
 'S1_C6_F289_V0251',
 'S1_C6_F289_V0252',
 'S1_C6_F289_V0254',
 'S1_C6_F289_V0255',
 'S1_C6_F289_V0257',
 'S1_C6_F290_V0258',
 'S1_C6_F394_V0306',
 'S1_C6_F394_V0308',
 'S1_C6_F394_V0309',
 'S1_C6_F404_V0344',
 'S1_C6_F404_V0345',
 'S1_C6_F404_V0347',
 'S1_C6_F404_V0348',
 'S1_C6_F404_V0349',
 'S1_C6_F404_V0350',
 'S1_C6_F404_V0351',
 'S1_C6_F404_V0352',
 'S1_C6_F404_V0353',
 'S1_C6_F404_V0354',
 'S1_C6_F404_V0355',
 'S1_C6_F404_V0356',
 'S1_C6_F405_V0361',
 'S2_C1_E284_V0039',
 'S2_C1_E290_V0042',
 'S2_C1_E350_V0086',
 'S2_C1_E353_V0088',
 'S2_C1_E384_V0110',
 'S2_C2_E384_V0127',
 'S2_C3_E290_V0057',
 'S2_C3_E323_V0091',
 'S2_C3_E384_V0125',
 'S3_C2_E658_V0150',
 'S3_C2_E717_V0260',
 'S3_C2_E717_V0261',
 'S3_C2_E718_V0262',
 'S3_C2_E719_V0270',
 'S3_C2_E719_V0272',
 'S3_C2_E719_V0273',
 'S3_C2_E719_V0274',
 'S3_C2_E719_V0275',
 'S3_C2_E723_V0300',
 'S3_C2_E723_V0301',
 'S3_C2_E725_V0309',
 'S3_C2_E737_V0355',
 'S3_C2_E764_V0417',
 'S3_C2_E764_V0424',
 'S3_C2_E769_V0438',
 'S3_C2_E791_V0517',
 'S3_C2_E792_V0526',
 'S3_C3_E524_V0333',
 'S3_C4_F719_V0080',
 'S3_C4_F720_V0082',
 'S3_C4_F720_V0083',
 'S3_C4_F720_V0084',
 'S3_C4_F720_V0087',
 'S3_C4_F720_V0088',
 'S3_C4_F720_V0091',
 'S3_C5_F719_V0153',
 'S3_C5_F719_V0154',
 'S3_C5_F719_V0156',
 'S3_C5_F719_V0157',
 'S3_C5_F719_V0158'}

# Joint table

In [27]:
salma_results = pd.read_csv("/media/eceo_scratch_haas001/results/prompting_mammalps-v2/LLM/qwen/Qwen3-8B-salma.csv").rename(columns={"Unnamed: 0":"query", "F1-score": "Agent+SALMA"}).set_index("query").drop("mIoU", axis=1)
oracle_results = pd.read_csv("/media/eceo_scratch_haas001/results/prompting_mammalps-v2/LLM/qwen/Qwen3-8B-oracle.csv").rename(columns={"Unnamed: 0":"query", "F1-score": "Agent+Oracle"}).set_index("query").drop("mIoU", axis=1)
clip_results = pd.read_csv("/media/eceo_scratch_haas001/results/prompting_mammalps-v2/CLIP4Clip/test/f1_queries.csv").rename(columns={"Unnamed: 0":"query", "F1-score": "CLIP4Clip"}).set_index("query")
intern_results = pd.read_csv("/media/eceo_scratch_haas001/results/prompting_mammalps-v2/InternVideo2/test/f1_queries.csv").rename(columns={"Unnamed: 0":"query", "F1-score": "InternVideo"}).set_index("query")

joint_results = (
    oracle_results
    .merge(salma_results, left_index=True, right_index=True)
    .merge(clip_results, left_index=True, right_index=True, how="left")
    .merge(intern_results, left_index=True, right_index=True, how="left")
    .sort_values(["Agent+Oracle", "Agent+SALMA", "CLIP4Clip", "InternVideo"], ascending=False)
)
joint_results

,Agent+Oracle,Agent+SALMA,CLIP4Clip,InternVideo
query,,,,
A fox reacting to a camera.,1.000000,1.000000,1.000000,1.000000
A juvenile roe deer suckling.,1.000000,1.000000,1.000000,0.997413
A juvenile roe deer preparing to suckle.,1.000000,1.000000,0.999354,0.996764
An adult female red deer escaping in sunny weather.,1.000000,1.000000,0.998061,0.998061
A fox sniffing.,1.000000,1.000000,0.984273,0.982940
A fox chasing prey.,1.000000,0.999354,1.000000,1.000000
A fox chasing prey in clear weather.,1.000000,0.999354,1.000000,1.000000
A roe deer participating in courtship in rainy weather.,1.000000,0.999354,0.027990,0.148148
A juvenile roe deer.,1.000000,0.998061,0.984273,0.965287
A wolf reacting to a camera.,1.000000,0.997413,0.688663,0.570111
An empty video.,1.000000,0.930233,0.151515,0.148148
An animal resting.,1.000000,0.857143,0.039139,0.095238
A video of an animal lying down while resting.,1.000000,0.857143,0.000000,0.400000
A wolf chasing prey.,1.000000,0.857143,0.000000,0.000000
A hare foraging.,1.000000,0.800000,0.010710,0.010309
A wolf chasing prey in a different weather condition from that in <vid>S2_C1_F573_V0093</vid>.,1.000000,0.800000,NaN,NaN
An adult male red deer rubbing its antlers on the ground.,1.000000,0.763158,0.211538,0.261905
An animal being vigilant while the weather is rainy or overcast.,1.000000,0.748663,0.584615,0.210035
An animal bathing.,1.000000,0.736842,0.000000,0.052863
A hare.,1.000000,0.727273,0.013514,0.000000
An adult male red deer being vigilant after vocalizing.,1.000000,0.701754,0.318841,0.607143
An animal bathing while grooming.,1.000000,0.695652,0.000000,0.017094
Rainy weather.,1.000000,0.684783,0.281899,0.359551
An animal participating in courtship.,1.000000,0.678261,0.347826,0.071429
An animal running.,1.000000,0.676806,0.217949,0.262877
A roe deer participating in courtship in clear weather.,1.000000,0.666667,0.007722,0.007772
A red deer resting in clear weather.,1.000000,0.666667,0.006006,0.000000
A video of two or more wolves.,1.000000,0.666667,0.000000,0.000000
A red deer foraging in rainy weather.,1.000000,0.638298,0.195187,0.182681
An animal being vigilant while the weather is clear or sunny.,1.000000,0.630915,0.262626,0.263711
An adult male red deer pawing the ground while wallowing.,1.000000,0.593750,0.187500,0.294118
A video of two or more animals.,1.000000,0.591640,0.222989,0.301370
An adult male red deer pawing the ground and rubbing its antlers on the ground while wallowing.,1.000000,0.588235,0.150943,0.250000
A fox foraging.,1.000000,0.571429,0.013514,0.000000
A mountain hare being vigilant.,1.000000,0.571429,0.006431,0.015666
An adult female roe deer running while participating in courtship.,1.000000,0.571429,0.000000,0.000000
A video of an animal drinking.,1.000000,0.492308,0.295082,0.076923
A roe deer grazing.,1.000000,0.470588,0.000000,0.027864
A wolf foraging.,1.000000,0.444444,0.015936,0.006780
A juvenile deer in rainy weather.,1.000000,0.444444,0.000000,0.018135
An animal being vigilant in a different weather condition from that in <vid>S2_C2_F536_V0066</vid>.,1.000000,0.403270,NaN,NaN
A video of two red deer.,1.000000,0.383562,0.183099,0.254826
A juvenile deer in clear or sunny weather.,1.000000,0.377953,0.126543,0.133333
An individual sharing at least one activity with any individual from <vid>S3_C2_E670_V0159</vid> but in a different weather condition.,1.000000,0.370968,NaN,NaN
A juvenile red deer playing.,1.000000,0.363636,0.100000,0.000000
An animal looking at a camera.,1.000000,0.358974,0.125000,0.058524
An adult male red deer reacting to a camera.,1.000000,0.344828,0.055046,0.100000
A video of three or more red deer.,1.000000,0.333333,0.193548,0.206897
A video of an individual sniffing while reacting to a camera.,1.000000,0.333333,0.000000,0.000000
An adult male red deer performing at least one different action while wallowing than with any individual of <vid>S3_C3_E524_V0327</vid>.,1.000000,0.301887,NaN,NaN
A juvenile red deer scratching its body.,1.000000,0.260870,0.188679,0.016000
A juvenile red deer shaking its head or body.,1.000000,0.250000,0.070175,0.000000
A roe deer foraging in sunny weather.,1.000000,0.250000,0.068966,0.075472
An animal reacting to a camera.,1.000000,0.235294,0.101124,0.085106
A video of two or more juvenile red deer.,1.000000,0.205128,0.170213,0.333333
An animal reacting to a camera in clear or sunny weather.,1.000000,0.192308,0.095238,0.087912
An individual doing at least one different action while reacting to a camera than with any individual of <vid>S1_C3_E144_V0060</vid>.,1.000000,0.176471,NaN,NaN
A video showing individuals from at least two different species.,1.000000,0.148148,0.000000,0.011811
An animal reacting to a camera in rainy or overcast weather.,1.000000,0.125000,0.078431,0.023810
An animal browsing.,1.000000,0.100000,0.036364,0.015424
An animal running while reacting to a camera.,1.000000,0.074074,0.061538,0.048077
An individual sharing at least one activity with any individual of the same species from <vid>S1_C4_F136_V0115</vid> but in a different weather condition.,1.000000,0.054286,NaN,NaN
An individual sharing at least one activity with any individual from <vid>S2_C1_F573_V0093</vid>.,1.000000,0.041885,NaN,NaN
An individual doing the same sequence of actions as the individual of <vid>S2_C1_E323_V0074</vid>.,1.000000,0.028986,NaN,NaN
Two or more animals reacting to a camera.,1.000000,0.000000,0.057143,0.000000
"An animal foraging, then reacting to a camera, and then returning to foraging.",1.000000,0.000000,0.045455,0.000000
A marten.,1.000000,0.000000,0.033058,0.000000
An adult roe deer sniffing.,1.000000,0.000000,0.021739,0.013106
A red deer resting in rainy weather.,1.000000,0.000000,0.006329,0.005168
An animal stretching its body.,1.000000,0.000000,0.003490,0.005682
A juvenile red deer nursing.,1.000000,0.000000,0.002821,0.000000
An adult female red deer nursing.,1.000000,0.000000,0.002747,0.005362
A juvenile red deer suckling.,1.000000,0.000000,0.002725,0.000000
An adult male red deer urinating while wallowing.,1.000000,0.000000,0.000000,0.105263
A chamois.,1.000000,0.000000,0.000000,0.021978
An adult male roe deer jumping.,1.000000,0.000000,0.000000,0.015152
A red deer browsing.,1.000000,0.000000,0.000000,0.011299
A mountain hare grazing.,1.000000,0.000000,0.000000,0.002699
An adult red deer browsing.,1.000000,0.000000,0.000000,0.002611
A chamois trotting.,1.000000,0.000000,0.000000,0.000000
A chamois being vigilant.,1.000000,0.000000,0.000000,0.000000
A video of one adult male and one adult female roe deer running while participating in courtship.,1.000000,0.000000,0.000000,0.000000
A red deer vocalizing in rainy weather.,1.000000,0.000000,0.000000,0.000000
A red deer participating in courtship in rainy weather.,1.000000,0.000000,0.000000,0.000000
A wolf chasing prey in overcast or rainy weather.,1.000000,0.000000,0.000000,0.000000
An adult roe deer reacting to a camera.,1.000000,0.000000,0.000000,0.000000
A video of three or more red deer reacting to a camera.,1.000000,0.000000,0.000000,0.000000
An adult male red deer doing the same sequence of actions while wallowing as any individual of <vid>S3_C2_E769_V0436</vid>.,1.000000,0.000000,NaN,NaN
A juvenile red deer performing at least one action in common while nursing with any individual in <vid>S1_C6_F394_V0310</vid>.,1.000000,0.000000,NaN,NaN
A juvenile red deer performing at least one action in common while nursing with any individual in <vid>S1_C6_F404_V0330</vid>.,1.000000,0.000000,NaN,NaN
A juvenile red deer performing at least one different action while nursing than with any individual in <vid>S1_C6_F404_V0330</vid>.,1.000000,0.000000,NaN,NaN
A video of three or more adult male red deer walking while foraging.,0.999354,0.992198,0.994812,0.994812
A video of two adult red deer vocalizing while participating in courtship.,0.994812,0.996114,0.567468,0.139256
An adult female red deer foraging and a juvenile red deer foraging.,0.965517,0.429907,0.194690,0.334802
An animal engaged in any activity other than foraging.,0.963780,0.779370,0.595822,0.596014
An individual sharing at least one activity with any individual from <vid>S1_C1_E66_V0152</vid> but of a different species.,0.957447,0.564706,NaN,NaN
A single adult red deer foraging only.,0.955186,0.801097,0.642732,0.650046
An adult red deer reacting to a camera.,0.945455,0.196721,0.103004,0.141176
A video of two or more red deer escaping.,0.941176,0.000000,0.000000,0.153846
An adult red deer standing with its head up while participating in courtship.,0.931818,0.720930,0.430108,0.493827
An individual doing at least one different action while reacting to a camera than with any individual of <vid>S1_C4_F173_V0137</vid>.,0.928571,0.161290,NaN,NaN
An adult female red deer running while participating in courtship.,0.928571,0.105263,0.086957,0.035665
An adult female red deer reacting to a camera.,0.882353,0.000000,0.034985,0.076923
An animal reacting to a camera and then running away.,0.880000,0.066667,0.048780,0.067227
A red deer foraging in sunny weather.,0.868421,0.651685,0.254545,0.341772
An adult male roe deer running while participating in courtship.,0.857143,0.000000,0.000000,0.000000
"Two or more red deer foraging, with at least one also being vigilant at some point.",0.844444,0.309091,0.086957,0.169231
An animal escaping from another animal of the same species that is chasing it.,0.800000,0.000000,0.000000,0.000000
An animal running while foraging.,0.770833,0.371859,0.112150,0.091133
A video of two adult female red deer walking while foraging.,0.758621,0.166667,0.166667,0.155340
A juvenile deer reacting to a camera.,0.727273,0.125000,0.000000,0.000000
An individual doing the same unique actions while reacting to a camera as any individual of <vid>S1_C3_E144_V0060</vid>.,0.720000,0.200000,NaN,NaN
A juvenile red deer doing the exact same activities as an adult female red deer.,0.687500,0.125000,0.015748,0.115183
An adult male red deer doing the same sequence of actions while wallowing as any individual of <vid>S3_C3_E524_V0327</vid>.,0.666667,0.666667,NaN,NaN
A juvenile red deer doing at least one different action than an adult female red deer.,0.660194,0.288136,0.119718,0.211111
An animal that is neither a red deer nor a roe deer.,0.590164,0.400000,0.050569,0.050761
A wolf chasing prey in clear or sunny weather.,0.571429,0.500000,0.003846,0.000000
An adult male red deer running while participating in courtship.,0.571429,0.105263,0.080000,0.030769
A juvenile red deer doing the exact same actions as an adult female red deer.,0.554217,0.108108,0.064516,0.037736
A video of one adult male and one adult female red deer running while participating in courtship.,0.470588,0.000000,0.012461,0.027523
An individual performing the same activities as any individual from <vid>S2_C2_E351_V0099</vid> but in a different weather condition.,0.467532,0.038922,NaN,NaN
A juvenile red deer walking while being vigilant.,0.454545,0.111111,0.067797,0.000000
An individual doing the same sequence of actions while reacting to a camera as any individual of <vid>S1_C4_F173_V0137</vid>.,0.444444,0.074074,NaN,NaN
An animal reacting to a camera and then foraging.,0.428571,0.000000,0.133333,0.000000
An adult male red deer doing the same unique actions while wallowing as any individual of <vid>S3_C3_E524_V0327</vid>.,0.333333,0.333333,NaN,NaN
An adult red deer lying down while participating in courtship.,0.333333,0.000000,0.000000,0.076923
A roe deer trotting while foraging.,0.318182,0.089744,0.055556,0.000000
An adult male red deer bathing while wallowing.,0.222222,0.125000,0.000000,0.037037
A roe deer foraging in rainy weather.,0.065934,0.057143,0.020305,0.009693
An adult red deer vocalizing while participating in courtship.,0.000000,0.000000,0.358491,0.478632
"An animal foraging, then reacting to a camera, and then running away.",0.000000,0.000000,0.038462,0.040816
An animal escaping from another animal of a different species that is chasing it.,0.000000,0.000000,0.005789,0.083333
An adult male red deer doing the same unique actions while wallowing as any individual of <vid>S3_C2_E524_V0087</vid>.,0.000000,0.000000,NaN,NaN
An individual doing the same sequence of actions while reacting to a camera as any individual of <vid>S1_C3_E144_V0060</vid>.,0.000000,0.000000,NaN,NaN
An individual doing the same unique actions while reacting to a camera as any individual of <vid>S1_C4_F173_V0137</vid>.,0.000000,0.000000,NaN,NaN

In [25]:
queries_w_vtag = [q.replace("<vid>", r"\vidtag{").replace("</vid>", r"}") for q in joint_results.index]

In [ ]:
print(*queries_w_vtag, sep="}\n"+r"\query{")

A juvenile roe deer preparing to suckle.}
\query{A fox sniffing.}
\query{A juvenile roe deer suckling.}
\query{An adult female red deer escaping in sunny weather.}
\query{A fox reacting to a camera.}
\query{A fox chasing prey.}
\query{A roe deer participating in courtship in rainy weather.}
\query{A fox chasing prey in clear weather.}
\query{A juvenile roe deer.}
\query{A wolf reacting to a camera.}
\query{An empty video.}
\query{A wolf chasing prey.}
\query{An animal resting.}
\query{A video of an animal lying down while resting.}
\query{A hare foraging.}
\query{A wolf chasing prey in a different weather condition from that in \vidtag{S2_C1_F573_V0093}.}
\query{An adult male red deer rubbing its antlers on the ground.}
\query{An animal being vigilant while the weather is rainy or overcast.}
\query{An animal bathing.}
\query{A hare.}
\query{An adult male red deer being vigilant after vocalizing.}
\query{An animal bathing while grooming.}
\query{Rainy weather.}
\query{An animal participating in courtship.}
\query{An animal running.}
\query{A red deer resting in clear weather.}
\query{A roe deer participating in courtship in clear weather.}
\query{A video of two or more wolves.}
\query{A red deer foraging in rainy weather.}
\query{An animal being vigilant while the weather is clear or sunny.}
\query{An adult male red deer pawing the ground while wallowing.}
\query{A video of two or more animals.}
\query{An adult male red deer pawing the ground and rubbing its antlers on the ground while wallowing.}
\query{A fox foraging.}
\query{A mountain hare being vigilant.}
\query{An adult female roe deer running while participating in courtship.}
\query{A video of an animal drinking.}
\query{A roe deer grazing.}
\query{A wolf foraging.}
\query{A juvenile deer in rainy weather.}
\query{An animal being vigilant in a different weather condition from that in \vidtag{S2_C2_F536_V0066}.}
\query{A video of two red deer.}
\query{A juvenile deer in clear or sunny weather.}
\query{An individual sharing at least one activity with any individual from \vidtag{S3_C2_E670_V0159} but in a different weather condition.}
\query{A juvenile red deer playing.}
\query{An animal looking at a camera.}
\query{An adult male red deer reacting to a camera.}
\query{A video of three or more red deer.}
\query{A video of an individual sniffing while reacting to a camera.}
\query{An adult male red deer performing at least one different action while wallowing than with any individual of \vidtag{S3_C3_E524_V0327}.}
\query{A juvenile red deer scratching its body.}
\query{A juvenile red deer shaking its head or body.}
\query{A roe deer foraging in sunny weather.}
\query{An animal reacting to a camera.}
\query{A video of two or more juvenile red deer.}
\query{An animal reacting to a camera in clear or sunny weather.}
\query{An individual doing at least one different action while reacting to a camera than with any individual of \vidtag{S1_C3_E144_V0060}.}
\query{A video showing individuals from at least two different species.}
\query{An animal reacting to a camera in rainy or overcast weather.}
\query{An animal browsing.}
\query{An animal running while reacting to a camera.}
\query{An individual sharing at least one activity with any individual of the same species from \vidtag{S1_C4_F136_V0115} but in a different weather condition.}
\query{An individual sharing at least one activity with any individual from \vidtag{S2_C1_F573_V0093}.}
\query{An individual doing the same sequence of actions as the individual of \vidtag{S2_C1_E323_V0074}.}
\query{An adult roe deer sniffing.}
\query{A chamois trotting.}
\query{An adult male roe deer jumping.}
\query{A marten.}
\query{An adult red deer browsing.}
\query{A chamois.}
\query{A chamois being vigilant.}
\query{A mountain hare grazing.}
\query{An animal stretching its body.}
\query{A red deer browsing.}
\query{A red deer resting in rainy weather.}
\query{A video of one adult male and one adult female roe deer running while participating in courtship.}
\query{An adult male red deer urinating while wallowing.}
\query{A red deer vocalizing in rainy weather.}
\query{A red deer participating in courtship in rainy weather.}
\query{A juvenile red deer nursing.}
\query{A juvenile red deer suckling.}
\query{An adult female red deer nursing.}
\query{A wolf chasing prey in overcast or rainy weather.}
\query{Two or more animals reacting to a camera.}
\query{An adult roe deer reacting to a camera.}
\query{A video of three or more red deer reacting to a camera.}
\query{An animal foraging, then reacting to a camera, and then returning to foraging.}
\query{An adult male red deer doing the same sequence of actions while wallowing as any individual of \vidtag{S3_C2_E769_V0436}.}
\query{A juvenile red deer performing at least one action in common while nursing with any individual in \vidtag{S1_C6_F394_V0310}.}
\query{A juvenile red deer performing at least one action in common while nursing with any individual in \vidtag{S1_C6_F404_V0330}.}
\query{A juvenile red deer performing at least one different action while nursing than with any individual in \vidtag{S1_C6_F404_V0330}.}
\query{A video of three or more adult male red deer walking while foraging.}
\query{A video of two adult red deer vocalizing while participating in courtship.}
\query{An adult female red deer foraging and a juvenile red deer foraging.}
\query{An animal engaged in any activity other than foraging.}
\query{An individual sharing at least one activity with any individual from \vidtag{S1_C1_E66_V0152} but of a different species.}
\query{A single adult red deer foraging only.}
\query{An adult red deer reacting to a camera.}
\query{A video of two or more red deer escaping.}
\query{An adult red deer standing with its head up while participating in courtship.}
\query{An individual doing at least one different action while reacting to a camera than with any individual of \vidtag{S1_C4_F173_V0137}.}
\query{An adult female red deer running while participating in courtship.}
\query{An adult female red deer reacting to a camera.}
\query{An animal reacting to a camera and then running away.}
\query{A red deer foraging in sunny weather.}
\query{An adult male roe deer running while participating in courtship.}
\query{Two or more red deer foraging, with at least one also being vigilant at some point.}
\query{An animal escaping from another animal of the same species that is chasing it.}
\query{An animal running while foraging.}
\query{A video of two adult female red deer walking while foraging.}
\query{A juvenile deer reacting to a camera.}
\query{An individual doing the same unique actions while reacting to a camera as any individual of \vidtag{S1_C3_E144_V0060}.}
\query{A juvenile red deer doing the exact same activities as an adult female red deer.}
\query{An adult male red deer doing the same sequence of actions while wallowing as any individual of \vidtag{S3_C3_E524_V0327}.}
\query{A juvenile red deer doing at least one different action than an adult female red deer.}
\query{An animal that is neither a red deer nor a roe deer.}
\query{A wolf chasing prey in clear or sunny weather.}
\query{An adult male red deer running while participating in courtship.}
\query{A juvenile red deer doing the exact same actions as an adult female red deer.}
\query{A video of one adult male and one adult female red deer running while participating in courtship.}
\query{An individual performing the same activities as any individual from \vidtag{S2_C2_E351_V0099} but in a different weather condition.}
\query{A juvenile red deer walking while being vigilant.}
\query{An individual doing the same sequence of actions while reacting to a camera as any individual of \vidtag{S1_C4_F173_V0137}.}
\query{An animal reacting to a camera and then foraging.}
\query{An adult male red deer doing the same unique actions while wallowing as any individual of \vidtag{S3_C3_E524_V0327}.}
\query{An adult red deer lying down while participating in courtship.}
\query{A roe deer trotting while foraging.}
\query{An adult male red deer bathing while wallowing.}
\query{A roe deer foraging in rainy weather.}
\query{An adult red deer vocalizing while participating in courtship.}
\query{An animal escaping from another animal of a different species that is chasing it.}
\query{An animal foraging, then reacting to a camera, and then running away.}
\query{An adult male red deer doing the same unique actions while wallowing as any individual of \vidtag{S3_C2_E524_V0087}.}
\query{An individual doing the same sequence of actions while reacting to a camera as any individual of \vidtag{S1_C3_E144_V0060}.}
\query{An individual doing the same unique actions while reacting to a camera as any individual of \vidtag{S1_C4_F173_V0137}.

In [29]:
print(*joint_results["InternVideo"].round(2).values, sep="\n")

1.0
1.0
1.0
1.0
0.98
1.0
1.0
0.15
0.97
0.57
0.15
0.1
0.4
0.0
0.01
nan
0.26
0.21
0.05
0.0
0.61
0.02
0.36
0.07
0.26
0.01
0.0
0.0
0.18
0.26
0.29
0.3
0.25
0.0
0.02
0.0
0.08
0.03
0.01
0.02
nan
0.25
0.13
nan
0.0
0.06
0.1
0.21
0.0
nan
0.02
0.0
0.08
0.09
0.33
0.09
nan
0.01
0.02
0.02
0.05
nan
nan
nan
0.0
0.0
0.0
0.01
0.01
0.01
0.0
0.01
0.0
0.11
0.02
0.02
0.01
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
nan
nan
nan
nan
0.99
0.14
0.33
0.6
nan
0.65
0.14
0.15
0.49
nan
0.04
0.08
0.07
0.34
0.0
0.17
0.0
0.09
0.16
0.0
nan
0.12
nan
0.21
0.05
0.0
0.03
0.04
0.03
nan
0.0
nan
0.0
nan
0.08
0.0
0.04
0.01
0.48
0.04
0.08
nan
nan
nan