In [ ]:
import json
from pathlib import Path
import pandas as pd
import numpy as np

from metrics import (
    F1_score,
    IoU,
)

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [ ]:
gt_videos_path = Path(
    "../benchmark/queries_and_videos_test.json"
)

all_possible_videos = list([f.stem for f in Path(
    "/media/EVO870/datasets/prompting-mammalps-v2/annotations/test"
).rglob("*.json")])

retrieved_results_path = Path(
    "/media/eceo_scratch_haas001/results/prompting_mammalps-v2/LLM/qwen/Qwen3-8B-salma.json"
)  # Path to the JSON file create by run.py

with open(gt_videos_path, "r") as f:
    gt_videos_cat = json.load(f)

gt_videos = {}
for cat in gt_videos_cat:
    
    for query, video_list  in gt_videos_cat[cat].items():
        gt_videos[query] = video_list

with open(retrieved_results_path, "r") as f:
    pred_videos = json.load(f)


with open("../benchmark/query_categories.json", "r") as f:
    query_categories = json.load(f)

query2eco_cat = {q: [] for q in gt_videos.keys()}
for cat in query_categories["ECOLOGY"]:
    for q in query_categories["ECOLOGY"][cat]:
        query2eco_cat[q].append(cat)

query2cv_cat = {q: [] for q in gt_videos.keys()}
for cat in query_categories["VISION"]:
    for q in query_categories["VISION"][cat]:
        query2cv_cat[q].append(cat)

# Overall performance

In [55]:
mF1, F1_queries = F1_score(gt_queries_videos=gt_videos, pred_queries_videos=pred_videos, all_videos=all_possible_videos)
mIoU, IoU_queries = IoU(gt_queries_videos=gt_videos, pred_queries_videos=pred_videos, all_videos=all_possible_videos)

In [56]:
print(f"F1-score (macro-avg.): {mF1:.2f}")
print(f"mean IoU: {mIoU:.2f}")

F1-score (macro-avg.): 0.28
mean IoU: 0.21

In [57]:
print(f"F1-score (macro-avg.) w/o Ref prompts: {np.nanmean([s for q, s in F1_queries.items() if '<vid>' not in q]):.2f}")
print(f"mean IoU w/o Ref prompts : {np.nanmean([s for q, s in IoU_queries.items() if '<vid>' not in q]):.2f}")

F1-score (macro-avg.) w/o Ref prompts: 0.30
mean IoU w/o Ref prompts : 0.23

# Performance per query et per category

In [32]:
results_df = pd.concat([
    pd.DataFrame.from_dict(IoU_queries, orient="index", columns=["mIoU"]),
    pd.DataFrame.from_dict(F1_queries, orient="index", columns=["F1-score"]),
    ], axis=1)

pd.set_option('display.max_rows', 150)
pd.set_option('display.max_colwidth', 90)
results_df.sort_values("mIoU", ascending=False)

,mIoU,F1-score
An adult female red deer escaping in sunny weather.,1.000000,1.000000
An adult male red deer doing the same sequence of actions while wallowing as any individual of <vid>S3_C2_E769_V0436</vid>.,1.000000,1.000000
A fox reacting to a camera.,1.000000,1.000000
A juvenile roe deer suckling.,1.000000,1.000000
A juvenile roe deer preparing to suckle.,1.000000,1.000000
A fox sniffing.,1.000000,1.000000
A juvenile roe deer.,0.998710,0.999354
A roe deer participating in courtship in rainy weather.,0.997419,0.998708
A fox chasing prey in clear weather.,0.997419,0.998708
A fox chasing prey.,0.997419,0.998708
A wolf reacting to a camera.,0.993548,0.996764
A juvenile red deer shaking its head or body.,0.984516,0.992198
A video of two adult red deer vocalizing while participating in courtship.,0.972903,0.986266
A video of three or more adult male red deer walking while foraging.,0.961290,0.980263
A hare foraging.,0.800000,0.888889
A video of an animal lying down while resting.,0.692308,0.818182
An animal resting.,0.692308,0.818182
An animal being vigilant in a different weather condition from that in <vid>S2_C2_F536_V0066</vid>.,0.672956,0.804511
A hare.,0.666667,0.800000
An empty video.,0.652174,0.789474
An animal being vigilant while the weather is rainy or overcast.,0.611570,0.758974
An animal engaged in any activity other than foraging.,0.609071,0.757047
A single adult red deer foraging only.,0.607889,0.756133
A wolf chasing prey.,0.600000,0.750000
Rainy weather.,0.596491,0.747253
A red deer foraging in rainy weather.,0.542553,0.703448
A roe deer participating in courtship in clear weather.,0.500000,0.666667
An adult male red deer doing the same sequence of actions while wallowing as any individual of <vid>S3_C3_E524_V0327</vid>.,0.500000,0.666667
A mountain hare being vigilant.,0.500000,0.666667
A video of two or more wolves.,0.500000,0.666667
An adult red deer standing with its head up while participating in courtship.,0.454545,0.625000
A red deer foraging in sunny weather.,0.453125,0.623656
An animal participating in courtship.,0.447059,0.617886
A red deer resting in clear weather.,0.428571,0.600000
An adult male red deer rubbing its antlers on the ground.,0.421875,0.593407
An animal being vigilant while the weather is clear or sunny.,0.414343,0.585915
An adult male red deer pawing the ground while wallowing.,0.400000,0.571429
A fox foraging.,0.400000,0.571429
An individual sharing at least one activity with any individual from <vid>S1_C1_E66_V0152</vid> but of a different species.,0.392157,0.563380
An adult male red deer pawing the ground and rubbing its antlers on the ground while wallowing.,0.363636,0.533333
An animal running.,0.341912,0.509589
An animal bathing while grooming.,0.333333,0.500000
An adult male red deer being vigilant after vocalizing.,0.302632,0.464646
An animal bathing.,0.297872,0.459016
A roe deer foraging in sunny weather.,0.285714,0.444444
A roe deer grazing.,0.285714,0.444444
A video of two or more animals.,0.269886,0.425056
An animal that is neither a red deer nor a roe deer.,0.257143,0.409091
A wolf chasing prey in clear or sunny weather.,0.250000,0.400000
An individual doing the same sequence of actions as the individual of <vid>S2_C1_E323_V0074</vid>.,0.250000,0.400000
An individual sharing at least one activity with any individual from <vid>S3_C2_E670_V0159</vid> but in a different weather condition.,0.243781,0.392000
A video of an animal drinking.,0.236111,0.382022
An adult female red deer foraging and a juvenile red deer foraging.,0.224299,0.366412
A wolf foraging.,0.222222,0.363636
A juvenile deer in clear or sunny weather.,0.206349,0.342105
An adult male red deer doing the same unique actions while wallowing as any individual of <vid>S3_C3_E524_V0327</vid>.,0.200000,0.333333
A juvenile deer in rainy weather.,0.200000,0.333333
An adult male red deer performing at least one different action while wallowing than with any individual of <vid>S3_C3_E524_V0327</vid>.,0.196078,0.327869
An adult male red deer reacting to a camera.,0.148148,0.258065
An animal running while foraging.,0.137546,0.241830
A video of three or more red deer.,0.136905,0.240838
An animal looking at a camera.,0.130435,0.230769
A marten.,0.125000,0.222222
A video of two red deer.,0.123153,0.219298
A video of two or more juvenile red deer.,0.122449,0.218182
A juvenile red deer doing at least one different action than an adult female red deer.,0.121739,0.217054
An animal reacting to a camera in clear or sunny weather.,0.120690,0.215385
An individual doing at least one different action while reacting to a camera than with any individual of <vid>S1_C3_E144_V0060</vid>.,0.118644,0.212121
An adult roe deer sniffing.,0.111111,0.200000
An animal reacting to a camera.,0.111111,0.200000
A juvenile red deer playing.,0.111111,0.200000
An individual doing the same unique actions while reacting to a camera as any individual of <vid>S1_C3_E144_V0060</vid>.,0.111111,0.200000
A juvenile red deer scratching its body.,0.103448,0.187500
An animal reacting to a camera and then running away.,0.102564,0.186047
A video of two or more red deer escaping.,0.100000,0.181818
An adult red deer reacting to a camera.,0.092308,0.169014
A video of an individual sniffing while reacting to a camera.,0.090909,0.166667
"Two or more red deer foraging, with at least one also being vigilant at some point.",0.088757,0.163043
A juvenile red deer doing the exact same activities as an adult female red deer.,0.075472,0.140351
An individual doing at least one different action while reacting to a camera than with any individual of <vid>S1_C4_F173_V0137</vid>.,0.072464,0.135135
An animal reacting to a camera in rainy or overcast weather.,0.071429,0.133333
A juvenile red deer walking while being vigilant.,0.066667,0.125000
A video of two adult female red deer walking while foraging.,0.060976,0.114943
A juvenile red deer doing the exact same actions as an adult female red deer.,0.053763,0.102041
A juvenile deer reacting to a camera.,0.052632,0.100000
An individual sharing at least one activity with any individual of the same species from <vid>S1_C4_F136_V0115</vid> but in a different weather condition.,0.039301,0.075630
An animal browsing.,0.037037,0.071429
An animal running while reacting to a camera.,0.033333,0.064516
An adult male red deer bathing while wallowing.,0.031250,0.060606
A video showing individuals from at least two different species.,0.031250,0.060606
A roe deer foraging in rainy weather.,0.028986,0.056338
A roe deer trotting while foraging.,0.027344,0.053232
An individual performing the same activities as any individual from <vid>S2_C2_E351_V0099</vid> but in a different weather condition.,0.025298,0.049347
An adult female red deer reacting to a camera.,0.022222,0.043478
An individual sharing at least one activity with any individual from <vid>S2_C1_F573_V0093</vid>.,0.021248,0.041612
A chamois being vigilant.,0.000000,0.000000
A chamois.,0.000000,0.000000
An adult red deer browsing.,0.000000,0.000000
An adult male roe deer jumping.,0.000000,0.000000
An animal stretching its body.,0.000000,0.000000
A mountain hare grazing.,0.000000,0.000000
A red deer browsing.,0.000000,0.000000
A red deer resting in rainy weather.,0.000000,0.000000
A red deer vocalizing in rainy weather.,0.000000,0.000000
An adult male red deer urinating while wallowing.,0.000000,0.000000
A red deer participating in courtship in rainy weather.,0.000000,0.000000
An adult female red deer running while participating in courtship.,0.000000,0.000000
An adult female roe deer running while participating in courtship.,0.000000,0.000000
An adult male roe deer running while participating in courtship.,0.000000,0.000000
A video of one adult male and one adult female red deer running while participating in courtship.,0.000000,0.000000
A video of one adult male and one adult female roe deer running while participating in courtship.,0.000000,0.000000
An adult male red deer running while participating in courtship.,0.000000,0.000000
An adult red deer lying down while participating in courtship.,0.000000,0.000000
An adult red deer vocalizing while participating in courtship.,0.000000,0.000000
A chamois trotting.,0.000000,0.000000
A juvenile red deer suckling.,0.000000,0.000000
A juvenile red deer nursing.,0.000000,0.000000
An adult female red deer nursing.,0.000000,0.000000
A wolf chasing prey in overcast or rainy weather.,0.000000,0.000000
A video of three or more red deer reacting to a camera.,0.000000,0.000000
An adult roe deer reacting to a camera.,0.000000,0.000000
Two or more animals reacting to a camera.,0.000000,0.000000
An animal escaping from another animal of the same species that is chasing it.,0.000000,0.000000
An animal escaping from another animal of a different species that is chasing it.,0.000000,0.000000
"An animal foraging, then reacting to a camera, and then returning to foraging.",0.000000,0.000000
"An animal foraging, then reacting to a camera, and then running away.",0.000000,0.000000
An animal reacting to a camera and then foraging.,0.000000,0.000000
A juvenile red deer performing at least one different action while nursing than with any individual in <vid>S1_C6_F404_V0330</vid>.,0.000000,0.000000
A juvenile red deer performing at least one action in common while nursing with any individual in <vid>S1_C6_F404_V0330</vid>.,0.000000,0.000000
A juvenile red deer performing at least one action in common while nursing with any individual in <vid>S1_C6_F394_V0310</vid>.,0.000000,0.000000
An adult male red deer doing the same unique actions while wallowing as any individual of <vid>S3_C2_E524_V0087</vid>.,0.000000,0.000000
An individual doing the same sequence of actions while reacting to a camera as any individual of <vid>S1_C3_E144_V0060</vid>.,0.000000,0.000000
An individual doing the same sequence of actions while reacting to a camera as any individual of <vid>S1_C4_F173_V0137</vid>.,0.000000,0.000000
An individual doing the same unique actions while reacting to a camera as any individual of <vid>S1_C4_F173_V0137</vid>.,0.000000,0.000000
A wolf chasing prey in a different weather condition from that in <vid>S2_C1_F573_V0093</vid>.,0.000000,0.000000

In [33]:
eco_cat_df = pd.DataFrame([query2eco_cat], index=["eco_cat"]).T
cv_cat_df = pd.DataFrame([query2cv_cat], index=["cv_cat"]).T
results_cat_df = results_df.merge(eco_cat_df, left_index=True, right_index=True).merge(cv_cat_df, left_index=True, right_index=True)

In [34]:
# Ecology categories
results_cat_df[["mIoU", "F1-score", "eco_cat"]].explode(["eco_cat"]).groupby("eco_cat").mean().T

eco_cat   CAMERA_REACTION    COMMON  COURTSHIP      RARE    SOCIAL
mIoU             0.149804  0.630031   0.260414  0.337257  0.273017
F1-score         0.196993  0.772803   0.327327  0.425771  0.326541

In [35]:
results_cat_df[["mIoU", "F1-score", "eco_cat"]].explode(["eco_cat"]).groupby("eco_cat").count().T

eco_cat   CAMERA_REACTION  COMMON  COURTSHIP  RARE  SOCIAL
mIoU                   28       2         27    48      36
F1-score               28       2         27    48      36

In [36]:
results_cat_df[["mIoU", "F1-score", "cv_cat"]].explode(["cv_cat"]).groupby("cv_cat").mean().T

cv_cat     COMPLEX  MULTI_ATTR  MULTI_INDIV  SINGLE_ATTR  VIDEO_COMPARISON
mIoU      0.173321    0.283342     0.157816     0.282278          0.174684
F1-score  0.238726    0.346988     0.210755     0.391673          0.236437

In [37]:
results_cat_df[["mIoU", "F1-score", "cv_cat"]].explode(["cv_cat"]).groupby("cv_cat").count().T

cv_cat    COMPLEX  MULTI_ATTR  MULTI_INDIV  SINGLE_ATTR  VIDEO_COMPARISON
mIoU           15          92           25           14                22
F1-score       15          92           25           14                22